### ISSUE TITLE
Share the santized Portage data with DCC

### ISSUE THREAD

**Issue by portagenetwork** [portagenetwork/roadmap#1]
- [x] UofA to share the santized version of the Portage production data with DCC. (https://github.com/ualbertalib/DMP_roadmap/pull/24)

**Comment by portagenetwork** [comment]
New data is available at:
https://github.com/portagenetwork/roadmap/tree/db_sanitization/portage_sanitized_data

**Comment by weiweishi** [comment]
@xsrust I just wonder, and in hope that you've already seen the dataset available here. Let me know if you have any questions.

**Comment by xsrust** [comment]
Hi @weiweishi   
Yep, I've been working with the above dataset, Thank you so much for sanitizing and uploading it.

I actually do have some questions/assumptions on the implimentation of the Translations in your live service that I'd like to double check.  They shouldn't affect the export of the translations in the initial step, but may have implications when we're re-associating the translations with the migrated DB-values.

I've noticed that the `Dmptemplate` objects have a locale, whereas `Versions` down through `QuestionFormat` do not.   Is it safe to assume that the `Dmptemplate`'s Locale applies to the associated `Version`, `Phase`, `Section`, and `Question` ?

For the other translated models, `QuestionFormat` and `Guidance`,  Is it safe to assume that the translation table locale is the opposite of the language used on the non-translated record?

Thanks
