### ISSUE TITLE
Dockerfile references the old version of ruby

### ISSUE THREAD

**Issue by nmacgreg** [portagenetwork/roadmap#101]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
My RPM is: dmp-3.0.0-6.x86_64

**Expected behaviour:**
Dateline, Dec 9, 2021, we updated the Staging environment with this new version, and Ruby to v2.6.6:
[root@southampton ~]# rpm -q ruby
ruby-2.6.6-0.el7.x86_64

I expected that the Dockerfile would be updated to the same version!

**Actual behaviour:**
The Dockerfile still references the old Ruby v2.5.8

**Steps to reproduce:**
No steps; just examine the Dockerfile

**Comment by pengyin-shan** [comment]
@nmacgreg thank you for pointing it out! I adjusted the ruby version for both Docker file accordingly. So far we use `Docker-production.yml` for the uat branch. I think we might gonna to update `Docker.yml` in the future.
