### ISSUE TITLE
Fix MySQL tests

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#103]
This issue has to do with our GitHub workflow.

The MySQL workflow is failing after we performed upgrades. We know that the tests pass on our local development environment so we should take some time to fix the tests on the workflow. 

The tests seem to fail due to unmet package dependencies. For example [https://github.com/portagenetwork/roadmap/actions/runs/1620185245](https://github.com/portagenetwork/roadmap/actions/runs/1620185245)

We could take a look at how DCC's [actions](https://github.com/DMPRoadmap/roadmap/actions) are configured and try to follow their example.

**Comment by pengyin-shan** [comment]
changes merged to integration
