### ISSUE TITLE
Update to Landing Page Text

### ISSUE THREAD

**Issue by robynnicholson** [portagenetwork/roadmap#105]
Request to update the text on the landing page - required changes outlined in the following Google doc (under 'Updated Content'):  https://docs.google.com/document/d/1UGiobPFLt2P0WXqIVWYbMS2w2T56UJ1YLM2QNoOGmnk/edit?usp=sharing.

**Comment by robynnicholson** [comment]
Hi @pengyin-shan, just circling back to this issue with a request for a slight edit: After talking with Lee we decided to take out the "Portage Network" reference in the text, and I've updated the Google doc accordingly (https://docs.google.com/document/d/1UGiobPFLt2P0WXqIVWYbMS2w2T56UJ1YLM2QNoOGmnk/edit?usp=sharing). 

We just want to remove "Portage Network" and "Reseau Portage" from the bracketed text in the first paragraph. Let me know if that is unclear, and apologies for the last minute change!

**Comment by pengyin-shan** [comment]
@robynnicholson no problem, I will make the change accordingly. Just a FYI, do you also want to take out the logo of Portage Network in README and Github wiki for the 3.0 release (I'm currently using both Allicance and Portage Network logo as the footer)?

Also as a note I will publish the change of this ticket to UAT and let you know once I'm done. The production version will not reflect this change until the 3.0 release next Friday.

> Hi @pengyin-shan, just circling back to this issue with a request for a slight edit: After talking with Lee we decided to take out the "Portage Network" reference in the text, and I've updated the Google doc accordingly (https://docs.google.com/document/d/1UGiobPFLt2P0WXqIVWYbMS2w2T56UJ1YLM2QNoOGmnk/edit?usp=sharing).
> 
> We just want to remove "Portage Network" and "Reseau Portage" from the bracketed text in the first paragraph. Let me know if that is unclear, and apologies for the last minute change!

**Comment by robynnicholson** [comment]
@pengyin-shan perfect, thank you! Yes I think we can take the Portage logo off the README and GitHub wiki for the 3.0 release There are still a lot of mentions of Portage on the platform itself (including the URL and support email), however long-term all references of Portage will eventually be removed so we might as well start now.

Happy to check it out in UAT once completed, feel free to ping me!

**Comment by robynnicholson** [comment]
Hi @pengyin-shan, just following up on this ticket with some expanded requests:
- Update text according to suggested edits in Google doc (under 'Updated Content'): https://docs.google.com/document/d/1UGiobPFLt2P0WXqIVWYbMS2w2T56UJ1YLM2QNoOGmnk/edit?usp=sharing (I believe you already made these changes, but just including for the sake of completeness)
- Change NDRIO logo in bottom ribbon to Alliance logo (high res versions attached)
- Remove Portage logo from bottom ribbon
- Change copyright in bottom ribbon from "2004 - 2022 Portage Network" to "2004 - 2022 Digital Research Alliance of Canada" ("Alliance de recherche numérique du Canada" in French)
![Alliance_logo_English-first_reversed (2)](https://user-images.githubusercontent.com/46638411/153288766-76878e65-c923-491d-a86b-bb8ed609c773.png)
![Alliance_logo_English-first (2)](https://user-images.githubusercontent.com/46638411/153288769-8c7e66eb-0a2e-465d-9ae8-dea7394d2536.png)

**Comment by pengyin-shan** [comment]
Closing this ticket. The branch has been merged to integration and sent to Neil for the 3.0 relase
