### ISSUE TITLE
Update project documentation

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#109]
The current README.md file is way out of date and it is also representing the current state of the main [codebase from DCC](https://github.com/DMPRoadmap/roadmap).

Updating the documentation includes:

README.md file

- [x] The current versions of the software we are using
- [x] Information about the function of the fork as a customization of the original code base with the requirements of the [Alliance](https://alliancecan.ca/)
- [x] All links should point to our own documentation including releases, installation, and troubleshooting guides. 
- [x] Include our own test badges for our tests instead of using the ones from [DMPRoadmap/roadmap](https://github.com/DMPRoadmap/roadmap)

Installation guide wiki page

- [x] Our development environment is handled with docker and it should be reflected on the wiki page
- [x] We are currently using secrets to handle sensitive information instead of the encrypted credentials
- [x] Links to Docker configuration need to be added

**Comment by pengyin-shan** [comment]
@lagoan for the MIT license, we currently have link to https://github.com/portagenetwork/roadmap/blob/deployment-portage/LICENSE.md, which doesn't have U of Alberta listed. Before I add U of Alberta in, should there be any legal process to be done first?

**Comment by pengyin-shan** [comment]
As a note, changing `About` part in Github repo description to DMP Assistant later.

**Comment by lagoan** [comment]
As I understand the MIT license we should be able to add the Alliance and the UofA but we should run that by the team, maybe we do need input from someone more versed in legal matters. @robynnicholson let's talk about this in our next check-in.

**Comment by pengyin-shan** [comment]
@robynnicholson @lagoan I updated README.md as an entry point of the project: https://github.com/portagenetwork/roadmap/tree/issue109, bottom of project page. Please let me know if it looks good to you and anything I miss, especially description about the Alliance. Thank you!    

Please note that some links will connect to empty wiki pages, which are the next thing I'm working on

**Comment by robynnicholson** [comment]
@pengyin-shan Looks good to me, just made a couple slight adjustments to the text and committed the changes. Thanks for getting that set up, great to have the documentation polished up!

**Comment by pengyin-shan** [comment]
@lagoan could you pls verify that:
1) the version for Ruby, Rails & MySQL makes senses? (we use MySQL8 for Github Action now after fixing the issue, thus I changed requirement to MySQL 8)
2) In contribution.md, which branch we want to have if we want to replace 'development' branch in description
3) What's the contact information we can give to users & developers/admins for support? I'll put it into Wiki
Thank you!

**Comment by pengyin-shan** [comment]
@lagoan for Docker image, do you want to update images to U of Alberta repo instead of your repo? I will update url in wiki then. 

And we suggest user to download `latest` image right instead of a specific version right?

**Comment by pengyin-shan** [comment]
@lagoan : when I was refreshing the setup process by running `bin/setup` and failed on one task `mime_types:load` because it is not available. I noticed that this task is for 3.1.0:
![Screen Shot 2022-01-13 at 14 44 41](https://user-images.githubusercontent.com/92752107/149398573-d8546c2a-8699-4ae3-b53a-4ffd2d5ac835.png)

So I tested by commenting out this step in `setup` file, then the `bin/setup` can be finished successfully:
![Screen Shot 2022-01-13 at 14 46 10](https://user-images.githubusercontent.com/92752107/149398782-c4cd1210-78e4-41ce-8405-074fb8d49996.png)

I want to confirm that this is what we will do for our 3.0 release. If so, I'll commit this change.

**Comment by pengyin-shan** [comment]
@lagoan to confirm that we are still using secrets and teach user how to setup, this is what I found under Rails 5.2.6:
![Screen Shot 2022-01-13 at 16 27 54](https://user-images.githubusercontent.com/92752107/149411838-c93f1103-5b2d-4111-aa1a-ecf1417f7e49.png)
![Screen Shot 2022-01-13 at 16 30 48](https://user-images.githubusercontent.com/92752107/149412130-dcf1ce57-6f50-438f-858c-27ec1996f8ed.png)

so credentials will make the terminal work instead of secrets under Rails 5.2.6. I think from Rails 5.2 credentials is the preferred way. Does this mean I should downgrade Rails to 5.1 and highlight it in README and Wiki?

**Comment by lagoan** [comment]
> @lagoan could you pls verify that:
> 
> 1. the version for Ruby, Rails & MySQL makes senses? (we use MySQL8 for Github Action now after fixing the issue, thus I changed requirement to MySQL 8)
> 2. In contribution.md, which branch we want to have if we want to replace 'development' branch in description
> 3. What's the contact information we can give to users & developers/admins for support? I'll put it into Wiki
>    Thank you!

1. The ruby and rails versions look OK. I don't think we need to change the mysql version in the documentation. If I understand correctly, the problem we had with the action was a dependency problem but the software does not require MySQL 8 to run correctly, I would leave it as it was before.
2. Lets change the mentions of the `development` branch to use the `integration` branch
3. We can use the `support@portagenetwork.ca` email account for now, if we start getting a lot of requests we can use another contact

**Comment by lagoan** [comment]
> @lagoan : when I was refreshing the setup process by running `bin/setup` and failed on one task `mime_types:load` because it is not available. I noticed that this task is for 3.1.0: ![Screen Shot 2022-01-13 at 14 44 41](https://user-images.githubusercontent.com/92752107/149398573-d8546c2a-8699-4ae3-b53a-4ffd2d5ac835.png)
> 
> So I tested by commenting out this step in `setup` file, then the `bin/setup` can be finished successfully: ![Screen Shot 2022-01-13 at 14 46 10](https://user-images.githubusercontent.com/92752107/149398782-c4cd1210-78e4-41ce-8405-074fb8d49996.png)
> 
> I want to confirm that this is what we will do for our 3.0 release. If so, I'll commit this change.

Our version is currently based on their `3.0.4` release, we should not have that step in our instructions.

**Comment by lagoan** [comment]
> @lagoan to confirm that we are still using secrets and teach user how to setup, this is what I found under Rails 5.2.6: ![Screen Shot 2022-01-13 at 16 27 54](https://user-images.githubusercontent.com/92752107/149411838-c93f1103-5b2d-4111-aa1a-ecf1417f7e49.png) ![Screen Shot 2022-01-13 at 16 30 48](https://user-images.githubusercontent.com/92752107/149412130-dcf1ce57-6f50-438f-858c-27ec1996f8ed.png)
> 
> so credentials will make the terminal work instead of secrets under Rails 5.2.6. I think from Rails 5.2 credentials is the preferred way. Does this mean I should downgrade Rails to 5.1 and highlight it in README and Wiki?

You are right, we are currently using secrets and will continue to do so in the near future. Even though secrets is deprecated it still works. As we move to the cloud we will very likely move to use credentials.

That part of the documentation should be modified to reflect our use of the secrets file

**Comment by pengyin-shan** [comment]
@robynnicholson I'd like to confirm with you our preferred way of providing support & communications to public, as well as social-network accounts, to post on 'Get Involved' section in our wiki.

A list of possible info we can post:
1) Twitter, Facebook or any social-network accounts
2) RSS feed resource or URLs to get update information of DMP Assistant
3) Any contact information besides `support@portagenetwork.ca` that you want public know
4) Any part of Development Roadmap that developer/admin should see (example: https://github.com/DMPRoadmap/roadmap/wiki/Development-roadmap)
5) Anything about translation/translation.io you want dev/admin to know (example: https://github.com/DMPRoadmap/roadmap/wiki/Translations)

**Comment by robynnicholson** [comment]
Hi @pengyin-shan :

1. Unfortunately, the DMP Assistant doesn't have a dedicated social network presence currently, so the support@portagenetwork.ca address is the best and most central contact for providing support. 
2. As far as communications, currently any announcements related to the DMP Assistant are published to the general Alliance website (https://alliancecan.ca/), so we can point to that for now. As part of our Communications strategy moving forward, I will be pushing for a dedicated DMP Assistant webpage where we might consider posting news items, release announcements, and blog posts (similar to what DCC does for DMPonline: https://www.dcc.ac.uk/dmponline). 
3. Again, I think support@portagenetwork.ca is the best contact to provide.
4. I would love to post parts of the Development Roadmap to the GitHub wiki - once the Roadmap draft is more formally finished, we can definitely touch base and see what that would look like.
5. I'm not sure about what we'd include about translation/translation.io, though I do like what the DMPRoadmap has - is that something we could adapt to the DMP Assistant? Perhaps we can chat about this more at our check-in on Tuesday.

**Comment by pengyin-shan** [comment]
> > @robynnicholson @lagoan I updated README.md as an entry point of the project: https://github.com/portagenetwork/roadmap/tree/issue109, bottom of project page. Please let me know if it looks good to you and anything I miss, especially description about the Alliance. Thank you!
> > Please note that some links will connect to empty wiki pages, which are the next thing I'm working on
> 
> All looks good! You mentioned that you would update the `About` part at a later time so I think that is the only thing that is missing.
> 
> One minor thing, I would add background color to the logos at the bottom of the page, maybe white?. I am currently using github's dark theme and the logos don't show up nicely.
> 
> ![image](https://user-images.githubusercontent.com/1537909/149412865-acb2b678-cb9b-4acf-8520-5c6426f3a7c9.png)

Got it, since Github markdown does not support style, I created two images for the dark and light theme, and they are now available for README based on the theme user chooses. Unfortunately, wiki doesn't support this feature, so it will only show the logo for the light theme.

**Comment by lagoan** [comment]
Sorry for not being clear regarding the logos on the bottom of the page. I think we can leave the one you had uploaded originally and add a white background to the image. This can be a simple change in an image editor. It does not matter if we see the white background on the dark theme.

**Comment by pengyin-shan** [comment]
> > @lagoan could you pls verify that:
> > 
> > 1. the version for Ruby, Rails & MySQL makes senses? (we use MySQL8 for Github Action now after fixing the issue, thus I changed requirement to MySQL 8)
> > 2. In contribution.md, which branch we want to have if we want to replace 'development' branch in description
> > 3. What's the contact information we can give to users & developers/admins for support? I'll put it into Wiki
> >    Thank you!
> 
>     1. The ruby and rails versions look OK. I don't think we need to change the mysql version in the documentation. If I understand correctly, the problem we had with the action was a dependency problem but the software does not require MySQL 8 to run correctly, I would leave it as it was before.
> 
>     2. Lets change the mentions of the `development` branch to use the `integration` branch
> 
>     3. We can use the `support@portagenetwork.ca` email account for now, if we start getting a lot of requests we can use another contact

Sounds good, I keep MySQL version as >=5 for now. I updated the contribution guide to use `integration` branch instead of `development`, and I'll update contact info in both README and wiki using the way you and Robyn suggested.

**Comment by pengyin-shan** [comment]
@lagoan to confirm the docker part...We want a updated version of `docker-compose.yml` (probably similar to the one in UAT) with `image:ualbertalib/dmp_roadmap` right? so that the user could download the yml file and run `docker-compose run --rm web /bin/bash` to start everything

**Comment by lagoan** [comment]
That sounds like a good plan if we want them to have the full version of the application running. Please try this approach to make sure it works.

We should also point them to our current development method of running `docker-compose` with the file `docker-compose-development.yml` which will only bring up the database and the user will need to run the rails server separately.

**Comment by pengyin-shan** [comment]
> 

@lagoan thank you for clarifying.  Another thing I want to make sure is the `dotenv` gem we are using. So far I know it is for load the `ENV` file and we are using `ENV` now for variables, such as `database_test_url: <%= ENV['DATABASE_TEST_URL'] %>`.  

So is it true that if a user want to set up local environment:
1) `.env` needs to be edited (which is controlled by dotenv gem)
2) see `secret.yml` to edit ENV variables for different environment (They will look at the `.env` file for corresponding value)
3) we are not using `rails secret:edit` to generate/edit the `secrets.yml.enc` file

**Comment by lagoan** [comment]
@pengyin-shan You are correct in that. For deployment, we are using the `secrets.yml` file. Our operations team edits that directly with Ansible. So it makes it easier for the two teams to have it this way. 

This will change once we start using credentials.

**Comment by pengyin-shan** [comment]
@lagoan when you have time, could you take a look at https://github.com/portagenetwork/roadmap/wiki/Installation#important-environment-variables and let me know if we have separate value for the keys listed in the table for user to use? Basically all the `default value` fields left in blank requires a API key to fill-in.

Another thing is that do we have any prepared data that we want user to import? Currently I follow the default data in seeds.rb and user will use the default account like `super_admin@example.com` to log in, and see an empty dashboard once finishing the  installation. Any sample data we want to give to user to show in their dashboard? 

Thank you!

**Comment by lagoan** [comment]
I think the environment variables look good. We could add default values on the secret file so that the application can run without these values entered. I will add a ticket for this

As for the initial data from the `seeds.rb` file, we will need to extend the seeds to include more data for users to play with. This will be needed for the sandbox environment.
