### ISSUE TITLE
Anomalies when using API

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#121]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

2.1.3+portage-1.0.19

**Expected behaviour:**

Plans with visibility set to `organization` should show all the responses for organization administrators.

**Actual behaviour:**

User reports a plan not showing the question response text.

**Steps to reproduce:**

Plan 8202 shows only the cover page. Can check plan 7996 for comparison.

**Comment by pengyin-shan** [comment]
Issue fixed (verified plan 8202 in v3.1.0. Clost this ticket).
