### ISSUE TITLE
Add rack_attack gem to stop attackers in their tracks

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#141]
We should look into adding the [rack-attack gem](https://github.com/rack/rack-attack) to stop malicious activity probing for attacks.

Use DMPTool's initializer configuration as a starting point for our implementation.

[https://github.com/CDLUC3/dmptool/blob/v3.4.0-beta/config/initializers/rack_attack.rb](https://github.com/CDLUC3/dmptool/blob/v3.4.0-beta/config/initializers/rack_attack.rb)

**Comment by pengyin-shan** [comment]
Had a conversation with Brian and he said he submitted a PR for this, and it will be in a future release (4.0.3 or 4.0.4). DMP Assistant can wait till then to update or check out codes for this specific feature from the main codebase after release.

**Comment by aaronskiba** [comment]
The rack-attack gem exists in upstream release v4.1.0 ([here](https://github.com/DMPRoadmap/roadmap/commit/7d9a1d592be200f7012115c4d6e2a0c745757b8a#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR112)).
