### ISSUE TITLE
Seed File Modification

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#149]
This issue documents the content and usage of the seed file for sandbox testing. 

Temp doc for seed:
https://docs.google.com/document/d/17BoJJ97y7xukVYmxyEzWS3Vbwk8vEhM7lOcQi3Z1tHs/edit

- [ ] Dragonfly modification to add org logos

**Comment by robynnicholson** [comment]
Hi @pengyin-shan, I've worked through the English sandbox environment on UAT and have the following comments/questions/requests:

1. On the landing page, will the Alliance logo appear on the footer when published?
2. For the Test Organization and Organisation de test, I think instead of any default (e.g., UBC/UoA logos), we could leave them without default logos, and then as part of the beta testing I'll provide the following test logos for users to add themselves.
![TestOrgLogo_EN (1)](https://user-images.githubusercontent.com/46638411/159026305-624d45ed-5acb-420e-9c10-aa89ad0b4ad5.jpg)
![TestOrgLogo_FR (1)](https://user-images.githubusercontent.com/46638411/159026320-a2f4d9c2-bcf9-4ff3-99d4-22dd646d3faf.jpg)
3. When adding/editing questions, I am unable to add a "Date" format question, receiving the following Error message: "Unable to create the question. You must have at least one option with accompanying text." - this also appears to be an issue in prod.
4. When editing a Template Phase, the "expand all"/"collapse all" function does not seem to work - same in production. Not critical, but flagging now.
5. Just to confirm, JSON download and plan ID number issues persist? Not critical for sandbox testing but just confirming.
6. As far as the Digital Research Alliance of Canada Organizational Profile, because the profile is still Portage Network in production, and the Guide and its screenshots all make reference to Portage, I'm wondering whether we should stick with Portage for the sake of consistency until we do the full rebranding. Thoughts?
7. Plans Download - HTTP ERROR 406: This page isn't working. Something that will adjust when published, perhaps?
9. Will we wipe what I've created through testing before publishing?

**Comment by robynnicholson** [comment]
From the run-through of the French sandbox on UAT:

1. When enabling Request feedback function (Demander des commentaires) via Organizational details (Renseignements sur l'organisme), the default message is still in English, but this is an existing issue with prod too and not critical for the sandbox testing necessarily.
2. Same issue with adding/editing question with Date format as English and in prod - "Error: Unable to create the question. You must have at least one option with accompanying text."
3. When I go to create a plan, if the organization does not have a template published, the option to select a template does not appear, instead creating a plan with the default template (Portage template). Just confirming this behaviour? Would it be possible to have all Portage templates available as options, just like in production? Perhaps this is something I can do from the Alliance Super Admin account.
4. Plan CSV download - errors with accented characters
![Screenshot 2022-03-18 125117](https://user-images.githubusercontent.com/46638411/159036925-d2ae8eb1-1532-44cf-9f40-8f0c30e814f5.png)
5. Same Plans download error message (HTTP ERROR 406: This page isn't working)
6. When trying to save an existing plan after adding/selecting themed guidance from the Project Details page, I received a "Error: It is impossible to save the plans." message. Saving themed guidance selections using a new plan I created worked fine. I removed the text I had entered in the Funder field (tried to enter free text as opposed to selecting from dropdown), and saving themed guidance selections worked. Tested it with a different plan and it seems if I enter free text in the Funder (Organisme subventionnaire) field and not select from the dropdown, I am unable to save the plan. When I select from dropdown, it works.
7. Download of Users is in English - not critical, but flagging here, I believe it is currently the same for prod too.
8. Usage Statistics downloads: "Totals"/Total usage CSV - in English; "Created_plans" or No. Plans Created CSV, Months is translated but not "No. Created Plans"; "Users_joined"/No. Users Joined CSV- translated, but same issue with accents. - All of these, again, non-critical I think, and also existing issues with prod as well, but just flagging here to document.

**Comment by pengyin-shan** [comment]
> Hi @pengyin-shan, I've worked through the English sandbox environment on UAT and have the following comments/questions/requests:
> 
> 1. On the landing page, will the Alliance logo appear on the footer when published?

_Yes, the alliance logo will show on footer after published. I'll ask Neil to add the image file to the sandbox server_

> 2. For the Test Organization and Organisation de test, I think instead of any default (e.g., UBC/UoA logos), we could leave them without default logos, and then as part of the beta testing I'll provide the following test logos for users to add themselves.
>    ![TestOrgLogo_EN (1)](https://user-images.githubusercontent.com/46638411/159026305-624d45ed-5acb-420e-9c10-aa89ad0b4ad5.jpg)
>    ![TestOrgLogo_FR (1)](https://user-images.githubusercontent.com/46638411/159026320-a2f4d9c2-bcf9-4ff3-99d4-22dd646d3faf.jpg)

_So currently, I set the logo image for both test organizations and Alliance (logo will appear once on production). I can remove the logos & contact info, and change abbreviations for all other organizations. Is this what you prefer?_
 
> 3. When adding/editing questions, I am unable to add a "Date" format question, receiving the following Error message: "Unable to create the question. You must have at least one option with accompanying text." - this also appears to be an issue in prod.

_Debugging it now_

> 4. When editing a Template Phase, the "expand all"/"collapse all" function does not seem to work - same in production. Not critical, but flagging now.

_I found it work on both production and uat by testing random plans...so it might happen to the specific plan only. Which plan do you find this problem with? (there could be a delay of collapsing and expanding though...the page needs time to load/unload data, so it depends on the speed of network._ 

> 5. Just to confirm, JSON download and plan ID number issues persist? Not critical for sandbox testing but just confirming.

_Yes, it is not fixed yet. I'll back to these issues once I finish this ticket. Please still suggest user download the csv instead for now_

> 6. As far as the Digital Research Alliance of Canada Organizational Profile, because the profile is still Portage Network in production, and the Guide and its screenshots all make reference to Portage, I'm wondering whether we should stick with Portage for the sake of consistency until we do the full rebranding. Thoughts?

_Both of the options work for me. I can change the Alliance to Portage and use the Portage logo also. Do you want me to do this?_

> 7. Plans Download - HTTP ERROR 406: This page isn't working. Something that will adjust when published, perhaps?

_The download function works on my side (tested on uat), so it probably also just apply to the specific plan. What's the plan you are seeing this issue?_

> 8. Will we wipe what I've created through testing before publishing?

_Yes, after moving to the sandbox environment (and my next deployment to uat), we will reload the database, so the 'new content' you created will be wiped and the user will see a fresh environment with three test accounts, a list of pre-created plans, Portage templates, and organizations. However, if you want to manually create something and keep it to the sandbox server, please feel free to send it to me. I'll write it to the database._

Hi @robynnicholson , please see my thoughts above.

**Comment by pengyin-shan** [comment]
> From the run-through of the French sandbox on UAT:
> 
> 1. When enabling Request feedback function (Demander des commentaires) via Organizational details (Renseignements sur l'organisme), the default message is still in English, but this is an existing issue with prod too and not critical for the sandbox testing necessarily.

_I think I can make it work...Can you provide the example plan that I can use to test?_

> 2. Same issue with adding/editing question with Date format as English and in prod - "Error: Unable to create the question. You must have at least one option with accompanying text."

_Yes, it is a functional issue, I'm looking at it. Once it fixed both English and French version will work_

> 3. When I go to create a plan, if the organization does not have a template published, the option to select a template does not appear, instead creating a plan with the default template (Portage template). Just confirming this behaviour? Would it be possible to have all Portage templates available as options, just like in production? Perhaps this is something I can do from the Alliance Super Admin account.

_I can make it work. So you want all portage templates open to all organizations right?_

> 4. Plan CSV download - errors with accented characters
>    ![Screenshot 2022-03-18 125117](https://user-images.githubusercontent.com/46638411/159036925-d2ae8eb1-1532-44cf-9f40-8f0c30e814f5.png)

_Fixed. Will be pushed to uat_

> 6. When trying to save an existing plan after adding/selecting themed guidance from the Project Details page, I received a "Error: It is impossible to save the plans." message. Saving themed guidance selections using a new plan I created worked fine. I removed the text I had entered in the Funder field (tried to enter free text as opposed to selecting from dropdown), and saving themed guidance selections worked. Tested it with a different plan and it seems if I enter free text in the Funder (Organisme subventionnaire) field and not select from the dropdown, I am unable to save the plan. When I select from dropdown, it works.

_I tested by using a saved plan (https://uat.library.ualberta.ca:3000/plans/71) and cannot replicate this issue (I guess it is a new plan). Can you provide the plan you were using? After a new plan is created, you can save as many times as you can for the free-text funder right?_

> 7. Download of Users is in English - not critical, but flagging here, I believe it is currently the same for prod too.

_Might be due to the limit of translation...let me check it._

> 8. Usage Statistics downloads: "Totals"/Total usage CSV - in English; "Created_plans" or No. Plans Created CSV, Months is translated but not "No. Created Plans"; "Users_joined"/No. Users Joined CSV- translated, but same issue with accents. - All of these, again, non-critical I think, and also existing issues with prod as well, but just flagging here to document.

_Fixed. Will be pushed to uat_

Hi @robynnicholson , please see my comments above.

**Comment by robynnicholson** [comment]
> > Hi @pengyin-shan, I've worked through the English sandbox environment on UAT and have the following comments/questions/requests:
> > 
> > 1. On the landing page, will the Alliance logo appear on the footer when published?
> 
> _Yes, the alliance logo will show on footer after published. I'll ask Neil to add the image file to the sandbox server_ 
> 
> > 2. For the Test Organization and Organisation de test, I think instead of any default (e.g., UBC/UoA logos), we could leave them without default logos, and then as part of the beta testing I'll provide the following test logos for users to add themselves.
> >    ![TestOrgLogo_EN (1)](https://user-images.githubusercontent.com/46638411/159026305-624d45ed-5acb-420e-9c10-aa89ad0b4ad5.jpg)
> >    ![TestOrgLogo_FR (1)](https://user-images.githubusercontent.com/46638411/159026320-a2f4d9c2-bcf9-4ff3-99d4-22dd646d3faf.jpg)
> 
> _So currently, I set the logo image for both test organizations and Alliance (logo will appear once on production). I can remove the logos & contact info, and change abbreviations for all other organizations. Is this what you prefer?_

I would remove the logos and contact info for the test organizations, but leave them for the Alliance. Administrators will be editing Organizational details for the test organizations but not for the Alliance necessarily. Abbreviations can probably remain as-is, testers can go in and change those if they wish.

> 
> > 3. When adding/editing questions, I am unable to add a "Date" format question, receiving the following Error message: "Unable to create the question. You must have at least one option with accompanying text." - this also appears to be an issue in prod.
> 
> _Debugging it now_
> 
> > 4. When editing a Template Phase, the "expand all"/"collapse all" function does not seem to work - same in production. Not critical, but flagging now.
> 
> _I found it work on both production and uat by testing random plans...so it might happen to the specific plan only. Which plan do you find this problem with? (there could be a delay of collapsing and expanding though...the page needs time to load/unload data, so it depends on the speed of network._

So this issue is while editing a Template Phase, not an individual plan. I'll try giving it time to load/unload.
> 
> > 5. Just to confirm, JSON download and plan ID number issues persist? Not critical for sandbox testing but just confirming.
> 
> _Yes, it is not fixed yet. I'll back to these issues once I finish this ticket. Please still suggest user download the csv instead for now_

No problem at all, thanks! 
> 
> > 6. As far as the Digital Research Alliance of Canada Organizational Profile, because the profile is still Portage Network in production, and the Guide and its screenshots all make reference to Portage, I'm wondering whether we should stick with Portage for the sake of consistency until we do the full rebranding. Thoughts?
> 
> _Both of the options work for me. I can change the Alliance to Portage and use the Portage logo also. Do you want me to do this?_
>
I think changing to Portage would be best for now, yes. Thank you! 
 
> > 7. Plans Download - HTTP ERROR 406: This page isn't working. Something that will adjust when published, perhaps?
> 
> _The download function works on my side (tested on uat), so it probably also just apply to the specific plan. What's the plan you are seeing this issue?_
> 
So I can download individual plans, but as an Admin when I go to the "Plans" page of the administrative interface and click "Download Plans" to download a CSV list of all plans at my organization, I receive the above error message. Let me know if I can clarify.

> > 8. Will we wipe what I've created through testing before publishing?
> 
> _Yes, after moving to the sandbox environment (and my next deployment to uat), we will reload the database, so the 'new content' you created will be wiped and the user will see a fresh environment with three test accounts, a list of pre-created plans, Portage templates, and organizations. However, if you want to manually create something and keep it to the sandbox server, please feel free to send it to me. I'll write it to the database._
> 
That's perfect, just checking! I don't think we need to save anything I created for the sandbox server, we'll want admins to be able to start from scratch for the most part.

> Hi @robynnicholson , please see my thoughts above.

Thanks @pengyin-shan! My responses above.

**Comment by robynnicholson** [comment]
> > From the run-through of the French sandbox on UAT:
> > 
> > 1. When enabling Request feedback function (Demander des commentaires) via Organizational details (Renseignements sur l'organisme), the default message is still in English, but this is an existing issue with prod too and not critical for the sandbox testing necessarily.
> 
> _I think I can make it work...Can you provide the example plan that I can use to test?_
> 
This is more to do with an administrative feature and not necessarily with individual plans. Basically, when signed into the Admin account  (Utilisateur test) for the French test organization using the French interface, when you go to the "Organizational details"  (Renseignements sur l'organisme) under the "Request feedback" (Demander des commentaires) tab, before you enable the feature, there is the following default text in English: "Hello %{user_name}.
Your plan "%{plan_name}" has been submitted for feedback from an administrator at your organisation. If you have questions pertaining to this action, please contact us at %{organisation_email}." Ideally this default text would be in French ("Bonjour %{user_name}. Votre plan %{plan_name} a été soumis pour commentaires d’un administrateur de votre organisation. Si vous avez des questions concernant cette action, veuillez communiquer avec nous à %{organisation_email}."), or no default text would be provided at all (there is also example text provided along the right-hand side). Let me know if I can clarify at all.

> > 2. Same issue with adding/editing question with Date format as English and in prod - "Error: Unable to create the question. You must have at least one option with accompanying text."
> 
> _Yes, it is a functional issue, I'm looking at it. Once it fixed both English and French version will work_
> 
> > 3. When I go to create a plan, if the organization does not have a template published, the option to select a template does not appear, instead creating a plan with the default template (Portage template). Just confirming this behaviour? Would it be possible to have all Portage templates available as options, just like in production? Perhaps this is something I can do from the Alliance Super Admin account.
> 
> _I can make it work. So you want all portage templates open to all organizations right?_
>
That's right, yes, just as it is in production. 
 
> > 4. Plan CSV download - errors with accented characters
> >    ![Screenshot 2022-03-18 125117](https://user-images.githubusercontent.com/46638411/159036925-d2ae8eb1-1532-44cf-9f40-8f0c30e814f5.png)
> 
> _Fixed. Will be pushed to uat_
> 
Great, thanks!

> > 6. When trying to save an existing plan after adding/selecting themed guidance from the Project Details page, I received a "Error: It is impossible to save the plans." message. Saving themed guidance selections using a new plan I created worked fine. I removed the text I had entered in the Funder field (tried to enter free text as opposed to selecting from dropdown), and saving themed guidance selections worked. Tested it with a different plan and it seems if I enter free text in the Funder (Organisme subventionnaire) field and not select from the dropdown, I am unable to save the plan. When I select from dropdown, it works.
> 
> _I tested by using a saved plan (https://uat.library.ualberta.ca:3000/plans/71) and cannot replicate this issue (I guess it is a new plan). Can you provide the plan you were using? After a new plan is created, you can save as many times as you can for the free-text funder right?_
> 
I've done another test and narrowed down the issue: it doesn't have anything to do with selecting themed guidance, there are two separate "Save" buttons on the Project Details page, one for selecting guidance on the right-hand side and one for the other administrative fields on the left-hand side. Trying to save the plan using the Save button on the left, if the "Funder" field is blank, I can save; if I start typing in the Funder field, and select from the dropdown menu, I can save; but if I type something in and do not select anything from the dropdown, wanting to leave the field value just as I typed it (free text), I get an error message ("Error: Unable to save the plan."). Let me know if there's further testing/clarification I can provide.

> > 7. Download of Users is in English - not critical, but flagging here, I believe it is currently the same for prod too.
> 
> _Might be due to the limit of translation...let me check it._
> 
> > 8. Usage Statistics downloads: "Totals"/Total usage CSV - in English; "Created_plans" or No. Plans Created CSV, Months is translated but not "No. Created Plans"; "Users_joined"/No. Users Joined CSV- translated, but same issue with accents. - All of these, again, non-critical I think, and also existing issues with prod as well, but just flagging here to document.
> 
> _Fixed. Will be pushed to uat_
> 
Great, thanks! 
> Hi @robynnicholson , please see my comments above.

Hi @pengyin-shan, thanks again! My responses above.

**Comment by pengyin-shan** [comment]
Update on issue list for current UAT:

For the English section issues:
1) Resolved
2) Resolved (Note: we might need to manually upload Portage image from UI after switching to sandbox environment). See UAT
3) Bug confirmed. I will deal with it in #167
4) It is a common bug that stays for a while. Need to discuss this with the Roadmap team. I make it as an external issue #166 
5) Will back to this issue after sandbox testing.
6) Resolved
7) Resolve
8) Resolved.

For the French section issues:

I was testing the French Accents Characters issue and noticed *Excel itself has trouble reading French accents characters from plain csv*. If you open the French csv in other program with UTF-8 encoding, such as text editor (TextEdit or Notepad will work), the  French Accents Characters should work correctly. 

**However, if you like to provide an excel-friendly format, we can add the `xsl` format in export option that have the same layout&content as csv, but looks good in excel**

1) Resolved. I used your post here in tranlsation.io but please still review it (I tagged)
2) Same bug. I will deal with it in #167
3) Resolved
4) Encoding issue...see above
5) Resolved
6) Should be resolved in UAT. I found that the issue apply to funder name that is a substring of the existing name (for example, 'test' cannot be saved because we already have orgs which name contains 'test', but 'test2' works). If you notice this issue happens again, please create a new issue and I'll update my navigation there.
7) Resolved. Translations tagged 'need review' in dmp-assistant-test.
8) Resolved. Translations tagged 'need review' in dmp-assistant-test.

**Comment by robynnicholson** [comment]
Hi @pengyin-shan, thanks so much for this succinct status summary, and for your work on all of these items! I have some final observations:

- Quick question: When editing Organizational Details, is the Administrator Contact automatically generated/autofilled?
- Usage Statistics seed data does not seem to be appearing - seeing "no data"
- For the French interface, item 1, the default suggested Request Feedback message, is still in English (e.g., "Hello %{user_name} ...etc). I verified the associated translation.io entry. As I mentioned, I don't think this one is critical to the Admin guide beta testing, we can bookmark it for later - it's included in the rolling [Translations doc](dmp.utilisateur.test.admin@engagedri.ca) so I have kept track of it.
- That's really interesting about the Excel French formatting, thanks for investigating! Maybe we can chat about it further at our check-in next week so I can fully understand, but by the sounds of it we may have a workaround available, which is great! Again, splitting hairs as far as requirements for beta testing.

**Comment by pengyin-shan** [comment]
@robynnicholson here are my answers:
> * Quick question: When editing Organizational Details, is the Administrator Contact automatically generated/autofilled?
**No they are not auto-filled. I add contact detail only for the three test orgs (the ones with test accounts). I remove the rest of org's contact info. We can do the same for the three test orgs, or use any pre-set contact info.**
> * Usage Statistics seed data does not seem to be appearing - seeing "no data"
**Ah sorry the statistics data needs to be manually triggered with a command. You should see it now.**
> * For the French interface, item 1, the default suggested Request Feedback message, is still in English (e.g., "Hello %{user_name} ...etc). I verified the associated translation.io entry. As I mentioned, I don't think this one is critical to the Admin guide beta testing, we can bookmark it for later - it's included in the rolling [Translations doc](dmp.utilisateur.test.admin@engagedri.ca) so I have kept track of it.
**I found the default feedback_message in database would overwrite the tranlsation.io one, so I adjusted in seed file to make all organization that has French langauge id to get the french default version. Now it should work**
> * That's really interesting about the Excel French formatting, thanks for investigating! Maybe we can chat about it further at our check-in next week so I can fully understand, but by the sounds of it we may have a workaround available, which is great! Again, splitting hairs as far as requirements for beta testing.
**sounds good, we can talk about adding this feature later.**

**Comment by pengyin-shan** [comment]
sandbox deployment is done. Close this issue for now
