### ISSUE TITLE
Remove the default 'Le' in the copyright footer

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#150]
Seems not to be a translation issue since the translation.io has the correct version. Notice similar behavior from the previous production version

**Comment by pengyin-shan** [comment]
Found the wrong translation when doing 3.1.0 migration... for `&copy; 2004 - %{year} %{org_name} `, the translation.io added an extra `Le` in its automated translation.

Adjusted in both dmp-assistant-test and dmp-assistant:
https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=aba57efb&query=%26copy%3B
https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=161fe6ed&query=%26copy%3B%202004%20-%20%25%7Byear%7D%20%25%7Borg_name%7D

**Comment by pengyin-shan** [comment]
@isawil can you pls confirm with the translator is 'Le' be correct or wrong? This is an old issue raised when Robyn was here, so I want to make sure it will be corrected in the next release:
<img width="486" alt="Screenshot 2022-11-15 at 11 54 40 AM" src="https://user-images.githubusercontent.com/92752107/201979444-409be37e-00b0-4a91-9b2b-9ece336e803c.png">

**Comment by shilowil** [comment]
I've forwarded this to our translator and will let you know when I hear back.

**Comment by pengyin-shan** [comment]
'Le' has been removed from tranlsation.io based on the translator's recommendation. Production will automatically pick the change. UAT fixed. Close this ticket.
