### ISSUE TITLE
New Terms of Use Page & Migration of Documentation from Portage website

### ISSUE THREAD

**Issue by robynnicholson** [portagenetwork/roadmap#152]
The Alliance Communications team is migrating content from Portage website (portagenetwork.ca) to new Alliance website (alliancecan.ca) and has requested that DMP Assistant documentation currently residing on Portage website be moved to DMP Assistant platform: [Terms of Use](https://portagenetwork.ca/tools-and-resources/dmp-assistant/dmp-assistant-terms-of-use/), [Institutional Customization Guide](https://portagenetwork.ca/tools-and-resources/dmp-assistant/dmp-assistant-custom-guide/), and FAQ (in development). 

Requests/Tasks:
- [x] Create new Terms of use page, to be navigated to from link in footer 
- [ ] Migrate Institutional Customization Guide/Administrator Guide to GitHub
- [ ] Explore GitHub-generated website option

**Comment by pengyin-shan** [comment]
@robynnicholson , just to confirm this is the re-branding task that we mentioned in the roadmap right? Any other detail that you would like to add? I see Terms of Use and Customization Guide is ready. How about FAQ?

**Comment by robynnicholson** [comment]
Hi @pengyin-shan, this is part of the rebranding task that is mentioned in the roadmap, but there are other items from the administrative side that will be required too, such as the new URL and support email address from Alliance Comms, the addition of the new logo/colour scheme from the branding firm, as well as the removal of "Portage" from the system template titles which will require communication with the administrator user community as any changes to customizable templates will require any administrator with an active customized version to "transfer customization" to make changes active.

**Comment by pengyin-shan** [comment]
@robynnicholson thank you! for the requirements you mentioned above, where can I find it? I didn't see an item called 'rebranding' in the change request registry, so is it separated into multiple tickets?

**Comment by robynnicholson** [comment]
@pengyin-shan Separated into multiple items, though the new logo/colour scheme is not yet represented as it was not so much a user request as much as an internal Alliance activity - I can add them though!

**Comment by pengyin-shan** [comment]
@robynnicholson Got it. thanks! I'll try to find them. And yeah if you could add the new logo/color information that would be great.

**Comment by pengyin-shan** [comment]
I created the test Github page for reference: https://portagenetwork.github.io. Currently still in the very basic mode (basic website template applied). We can add any page or content as we want

**Comment by pengyin-shan** [comment]
see https://github.com/portagenetwork/roadmap/issues/331 for the rebranding introduction. This ticket can be re-evaluated and passed to the new developer.

**Comment by closenma** [comment]
Reviewing this issue, we've resolved most of this. May reopen discussion on migration of administrator guide at a later date.
