### ISSUE TITLE
Plan Sharing Invitation Links & Account Creation Access: Unexpected Behaviours

### ISSUE THREAD

**Issue by robynnicholson** [portagenetwork/roadmap#163]
Related to previously closed ticket #83 (Error in email collaboration link; [summary of previous tickets](https://docs.google.com/document/d/1Sl8FSnHU5A7zbf32cFFYr0z0qeD8YPLRDjVegcoAQ1s/edit?usp=sharing)), where configuration of URL was an issue, new issue raised where user is unable to complete account creation or sign in due to error ("You have a pending invitation, accept it to finish creating your account."). 

Expected behaviour: Users without existing accounts are invited to collaborate on a plan via email; Link in email invites users to create an account to access the plan; System automatically creates placeholder account for the email address, with "First Name Last Name" values; user finishes account creation process by changing "First Name Last Name"; User logs into newly confirmed account and is able to access the plan that was shared with them via their dashboard.

Actual behaviour: When expected behaviour process is interrupted, unexpected results occur. Most recent example (2022-03-16): User reports that invitation to collaborate on a plan link is not working for them (https://assistant.portagenetwork.ca/users/invitation/accept?invitation_token=tW6Q1_asCKqWyqL444VZ), and when they attempt to create an account through the platform itself, they receive an error message that states "You have a pending invitation, accept it to finish creating your account." 

Duplication of issue in production (via @pengyin-shan):
1) I archived one of my personal accounts. 
2) I shared a plan with this account without logging out from the admin account. I got the same message 'You are already signed in as another user. Please log out to activate your invitation.' 
3) I tried to log in using a personal account, got the messageYou have a pending invitation, accept it to finish creating your account. 
4) I tried to finish the account creation process using the form on the landing page. Finish successfully and see the shared plan. (Since my personal account has been used before, I didn't see the First Name Last Name page).

Requirements: More information/testing about users' behavior because some actions lead to correct results while some other actions are throwing 'invalid token error'.  For now, we can use the 'redoing the invitation after deleting and creating the new account' alternative solution.

**Comment by pengyin-shan** [comment]
Close this issue since we are not receiving invalid token error reports anymore. We can re-open this if we see similar problem happening again
