### ISSUE TITLE
Collapse/Expand Not Work in Creating Template Page

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#166]
data-parent is not matching the panel id, but id is currently necessary for saving the template. Asked Brian in Slack about the comment 4 years ago.
![Screen Shot 2022-03-23 at 11 48 55](https://user-images.githubusercontent.com/92752107/159750134-99d48ba5-c7ed-4607-9d26-6501bc609168.png)
![Screen Shot 2022-03-23 at 11 31 59](https://user-images.githubusercontent.com/92752107/159750138-b5b7a2f3-84d7-4dd5-a11e-b0b6e4c2cde7.png)

**Comment by pengyin-shan** [comment]
@robynnicholson I just deployed to uat. Please test and let me know if it works for you. 

Since I adjusted code that affects all collapse/expand feature, If you could, please test as many collapse/expand functions in the dmp assistant as you can find (i tested many but I want to make sure I didn't miss anything).

**Comment by robynnicholson** [comment]
@pengyin-shan tested all the collapse/expand functions I know of in the user interface in uat, all looks good to me!

**Comment by pengyin-shan** [comment]
> @pengyin-shan tested all the collapse/expand functions I know of in the user interface in uat, all looks good to me!

Thank you for testing! this fix will be added to the next release (3.0.4+portage-3.0.9)
