### ISSUE TITLE
Date Format Question Forcing Adding Option with Accompanying Text

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#167]
When adding/editing questions, I am unable to add a "Date" format question, receiving the following Error message: "Unable to create the question. You must have at least one option with accompanying text." - this also appears to be an issue in prod.

@robynnicholson just want to confirm what this issue is expected to be, should be date format question go without option naturally, or it should have the option field available to the user?

Currently, the error is because the option field is not available to the user, but it requires the user to input text when saving.

**Comment by robynnicholson** [comment]
So, as an Admin, when I'm creating/editing a template and creating/editing a question, when I select "Date" for Anwer format, leave "Display additional comment area" checked by default, and enter both Example answer and Guidance text (see screenshot below), when I try to save the question, I receive an "Error: Unable to create the question. You must have at least one option with accompanying text." 
![Screenshot 2022-03-23 152643](https://user-images.githubusercontent.com/46638411/159770285-c914b138-928b-4f78-9bdb-118e8b3f0b93.png)

I think in plain language, the expectation is that the Date format question would prompt users to select a date from a dropdown calendar (not sure the technical term here!), like they do on the Project Details page:
![Screenshot 2022-03-23 154542](https://user-images.githubusercontent.com/46638411/159775557-64d09e82-5a76-469b-a92d-2876560c988a.png)

As discussed in Slack, the Date question format is not supposed to have option fields for user to fill, which checkbox or radio button requires. It only needs the ‘additional comment area’ checkbox available.

**Comment by pengyin-shan** [comment]
The issue actually comes from the data side, not the coding side. In the database, the `option_based` is set to TRUE for the date question type, which itself is not. I changed the seed file for the sandbox testing, so in the sandbox, this issue will disappear (you will see soon in uat).

For production, @robynnicholson I can let Neil know about this issue and adjust the database accordingly (either he will do or I can do it easily). I don't think any plan now is using the Date question, so this will not affect any existing plan.

**Comment by pengyin-shan** [comment]
resolved on both uat and prod
