### ISSUE TITLE
Organization type(s) Floatover Text Update: Incorrect Contact & Translation

### ISSUE THREAD

**Issue by robynnicholson** [portagenetwork/roadmap#172]
On the "Organization details" page, the tooltip floatover text requires updating to reflect the correct contact information: support@portagenetwork.ca, not "info@alliancecan.ca". 
![Screenshot 2022-04-01 115604](https://user-images.githubusercontent.com/46638411/161289404-c3b3a279-088a-455b-97d8-584e57e19659.png)

Additionally, the text is not translated on the French interface.
![Screenshot 2022-04-01 115546](https://user-images.githubusercontent.com/46638411/161289388-f8f8f061-c646-4273-808c-551b9e291c3d.png)

**Comment by pengyin-shan** [comment]
In production & sandbox now. Close this issue
