### ISSUE TITLE
Not authorized to perform action error when copying local template

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#18]
When click on "copy" was redirected to the Dashboard with a message indicating "not authorized to perform this action", but when went back to template listing, the copy was there.. For instutitions Western University and University of Guelph

**Comment by lagoan** [comment]
@pengyin-shan is this still an issue ?

**Comment by pengyin-shan** [comment]
Not seeing the error after the 3.0 release. Close this issue for now.
