### ISSUE TITLE
NEED VALIDATION: emails's language is based on user's choice on UI, instead of system default language and user's primary language

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#196]
Need to confirm this logic. The user mailer seems to send emails based on the system's default language. Will validate on the current version and 3.1.0 migrated version.

**Comment by pengyin-shan** [comment]
might be caused by the sanitization method. pending validation

**Comment by pengyin-shan** [comment]
@isawil : please verify if this issue is still in the 3.1.0 version. If so, please feel free to assign this ticket to the new developer, otherwise, you can close this issue.

**Comment by lagoan** [comment]
We need to verify that we have it so the email is sent in the language the UI is currently set to.
