### ISSUE TITLE
Exploratory software update: NodeJS

### ISSUE THREAD

**Issue by nmacgreg** [portagenetwork/roadmap#208]
I'm excited to report that NodeJS v16.x has recently (Jan '22) been added to the EPEL repository, where it's been getting regular (monthly) updates.   DMP in Staging & Production is currently running v12.22.12 of NodeJS, but v12.x recently fell off the "Maintenance" track (ref:[NodeJS Releases](https://nodejs.org/en/about/releases/)).

At your leisure, I'd like to consider updating to this v16.   It perhaps doesn't require any code changes on your part.  This is already complete in the "library-cms" project.  I suspect  the steps to get this completed are simply for me to:

- adjust the Dockerfile controlling the build-environment
- run the build / copy updated RPM to Staging repo
- adjust the Ansible playbook to remove the old  (v12.x) repo
- apply the Ansible playbook, to apply both the updated RPM for DMP, and update NodeJS from v12 to v16
- test the app in Staging

I have one question: what version of NodeJS are you running in the Development environment? 
( Hmmm, I think the answer is v12.x based on this line from the [Dockerfile](https://github.com/portagenetwork/roadmap/blob/deployment-portage/Dockerfile): 
`RUN curl -sL https://deb.nodesource.com/setup_12.x | bash`
... but I don't know if you're holding that back because of my restriction, or because of a restriction within the app.)

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
DMP v3.0.12

**Comment by pengyin-shan** [comment]
@nmacgreg , our development version of node is version 12 (My local machine is using 12.22.7). 

About the upgrade: I haven't tested what's going to change if we upgrade to node 16 now. I doubt DMP Assistant might going to see issues referring to my last upgrade experience of node from v10 fo v12, but I'll add this into our consideration of the next version upgrade.

**Comment by pengyin-shan** [comment]
@nmacgreg As a follow-up, for the upcoming 3.1.0 version (Feb 22), both my local machine and UAT is using node 16, and we see no problem. 

I understand that it could be too risky to do this node upgrade all once in this huge 3.1.0 release. Thus you can talk to @lagoan to think about node upgrades in 3.1.1 or future versions, I see no problem with it.

**Comment by lagoan** [comment]
@pengyin-shan we should definetly focus on finishing up everything for this major upgrade. Having said that, after the release and if you are able, could you test rebuilding the packages from scratch in the docker container using node 16. I don't think it would be a problem and should be easy enough to do with a small change in the docker file.

**Comment by pengyin-shan** [comment]
@lagoan ok, I will see if I still have time after 3.1.0 release on Feb 22 and clean out my current issues. If so, @nmacgreg we can do a small minor version upgrade, just for node 16.

**Comment by pengyin-shan** [comment]
I don't think I have time to do that node 16 upgrade... The new developer could take care of this in the 3.1.1 upgrade. We should see any issue with it since the main codebase is also using node 16.

**Comment by aaronskiba** [comment]
`4.0.2+portage-4.0.0` will upgrade to node v16.
