### ISSUE TITLE
In Dockerfile, multiple 'apt-get update' commands

### ISSUE THREAD

**Issue by nmacgreg** [portagenetwork/roadmap#213]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3.0.12

**Expected behaviour:**
In the Dockerfile, there are 2 statements which run , ```apt-get update```.  Once should be enough!

**Actual behaviour:**
Line 4: ```4 RUN apt-get update -qq && \```
Line 30: ```30 RUN apt-get update && apt-get install -y yarn```

**Steps to reproduce:**
Use eyeballs!

**Comment by pengyin-shan** [comment]
From what I understand (pls correct me if I'm wrong), the second apt-get is to force the environment to fix environment after installing node 12, so we can then install yarn.
I guess that we, at one time long ago, want DMP Assisant running in node 12 only. 

We can remove the extra step after upgrading to node 16 (i.e. use the system node directly)

**Comment by pengyin-shan** [comment]
@isawil : you can assign this ticket to the new developer, we could combine this with the node 16 upgrade.

**Comment by aaronskiba** [comment]
This issue still exists, but I am closing it and adding it's details to issue [#556 Update Docker Setup For Development](https://github.com/portagenetwork/roadmap/issues/556).
