### ISSUE TITLE
Change plan saving message in 'Write Plan' section to a more clarified version

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#241]
This ticket is created as an improvement for a user's plan saving problem (submitted via web form). User so far only see 'Saving...' and 'Answered by...' messages after saving the plan successfully:

![Screenshot 2022-11-04 at 11 12 02 AM](https://user-images.githubusercontent.com/92752107/200009589-ba30fd96-bb74-450d-a310-751e5699033d.png)

It could be very misleading because the user was stuck on the 'Saving' message and no explicit guidance showing that **if the user turns to other tabs now, the content in the rich text box will be lost and unrecovered**.

Thus a more clear version of the message is required. Users need to see something like *Saving...please do not refresh your page or change to other tab* and *Your plan has been successfully saved*.

**Comment by pengyin-shan** [comment]
(PR has been submitted to the main codebase: https://github.com/DMPRoadmap/roadmap/pull/3232)
Updated both `Saving...` message and error-saving message to explicitly tell the user to save the plan to a separate file before refreshing the page. 

Users will only see these messages *either they are stuck with the Saving... message (which means an error is happening) or an error occurred directly*, so regular users **won't be affected by this update**. I made this change only for users who got errors like Ann.

1) For error message:
![Screenshot 2022-11-08 at 2 31 13 PM](https://user-images.githubusercontent.com/92752107/200663194-3d6e6e4b-352c-4bd2-ac38-bb228b51bd4f.png)
2) For saving... message (very long, but users normally skim through it if their plan is saved successfully, so it won't affect regular user experience)
![Screenshot 2022-11-08 at 3 12 25 PM](https://user-images.githubusercontent.com/92752107/200665561-617ee190-40fe-4253-9a47-983a7de59a53.png)

-----
@isawil if the wording looks good to you, then we need following translations (I added `needs-review` tag):

1. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=1d18cae3&query=Plan%20writing%20error%20related%20to%20%25%7Btool_name%7D
2. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=04bbeab0&query=Saving...Please%20do%20
3. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=88b880b1&query=If%20you%20stuck%20on%20this%20message%2C%20p
4. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=02df45ff&query=Sorry%2C%20we%20had%20trouble%20saving%20your%20data
5. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=83a3ec75&query=Save%20your%20plan%20content%20to%20a%20separate%20file%20now.%20You%20will

**Comment by shilowil** [comment]
@pengyin-shan All translations should now be added to the translation.io tickets!

**Comment by pengyin-shan** [comment]
Translation done and the code-side changes will be merged in version 3.1.0
