### ISSUE TITLE
Unmanaged organization should not appear in any 'select organization' list

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#260]
Will remove unmanaged organizations from the organization type-in list when the user creates a new account:

<img width="500" alt="Screenshot 2022-11-16 at 4 31 26 PM" src="https://user-images.githubusercontent.com/92752107/202298719-6888050e-bbaa-4708-9b4c-173c98895535.png">

Meanwhile, @isawil can you pls take a look at the whole application (you can do this on uat: https://uat.library.ualberta.ca:3000/) and _see if anywhere else also has an organizational dropdown list_? I'll modify them to show managed org only. 

As a note, currently, the 'Create Plan' page and 'Statistics' page have the organizational list only showing managed org.

- [x] #275

**Comment by shilowil** [comment]
Sorry this is so late! I'm also seeing a drop-down list on the "Templates" page, but am unsure if this is just something visible to the superadmin.

**Comment by pengyin-shan** [comment]
> Sorry this is so late! I'm also seeing a drop-down list on the "Templates" page, but am unsure if this is just something visible to the superadmin.

I see, can you put a screenshot here? If that's also a place that needs unmanaged organization to be removed from the list, I'll apply changes to it.

**Comment by shilowil** [comment]
Yup -- here it is:

![image](https://user-images.githubusercontent.com/30664432/204370909-4b69dfec-fdc4-4ae3-b291-e986bbacfab6.png)

**Comment by pengyin-shan** [comment]
> Yup -- here it is:
> 
> ![image](https://user-images.githubusercontent.com/30664432/204370909-4b69dfec-fdc4-4ae3-b291-e986bbacfab6.png)

Sorry where is this screenshot coming from? You said in Templates page right? How you got there?

**Comment by pengyin-shan** [comment]
> > Yup -- here it is:
> > ![image](https://user-images.githubusercontent.com/30664432/204370909-4b69dfec-fdc4-4ae3-b291-e986bbacfab6.png)
> 
> Sorry where is this screenshot coming from? You said in Templates page right? How you got there?

Oh never mind, I found it. The templates is OK since it doesn't show **unmanaged organization**. For example, you won't see OMAFRA many times in this list

**Comment by pengyin-shan** [comment]
> > > Yup -- here it is:
> > > ![image](https://user-images.githubusercontent.com/30664432/204370909-4b69dfec-fdc4-4ae3-b291-e986bbacfab6.png)
> > 
> > 
> > Sorry where is this screenshot coming from? You said in Templates page right? How you got there?
> 
> Oh never mind, I found it. The templates is OK since it doesn't show **unmanaged organization**. For example, you won't see OMAFRA many times in this list

Hold on..I noticed my local version is different from the remote version. I'll check if this is due to some uncommitted changes

**Comment by pengyin-shan** [comment]
As a side note for navigation, the form on the Contributor page does not have unmanaged org listed:
<img width="982" alt="Screenshot 2022-11-28 at 5 36 28 PM" src="https://user-images.githubusercontent.com/92752107/204395511-46fd1472-6e74-4de8-be91-a6fbccff31db.png">.

Will keep this in mind.

**Comment by pengyin-shan** [comment]
@isawil : when you have time, pls test the following in uat:

1) Contributors should be able to add/switch organizations now.

2) All org selectors (in registration, create plan,... all pages except the creating new organization page) should not include any unmanaged organization.

3) Adding a new organization page will have a SLOWER org selector, because it is configured to query external organizations as well. Only this page should include unmanaged organizations because we want the super admin to be reminded that such an organization already exists.

**Comment by pengyin-shan** [comment]
> @isawil : when you have time, pls test the following in uat:
> 
> 1. Contributors should be able to add/switch organizations now.
> 2. All org selectors (in registration, create plan,... all pages except the creating new organization page) should not include any unmanaged organization.
> 3. Adding a new organization page will have a SLOWER org selector, because it is configured to query external organizations as well. Only this page should include unmanaged organizations because we want the super admin to be reminded that such an organization already exists.

Pls let me know if any org selector doesn't follow this rule.

**Comment by shilowil** [comment]
Results of the test:

1. This works -- thanks!
2. I'm not seeing unmanaged orgs on any of these pages, although the orgs that show up differ based on page (I couldn't add UofA when selecting a contributor organization, though I could in all other pages)
3. Org selector is slower

**Comment by pengyin-shan** [comment]
Thanks @isawil ! Yes adding a new organization page did have a slower selector since it needs to query ror.org, so it is expected. You will need to enter the full name, wait a little bit, then see if the result is returned or not. The regular users won't be affected by this behavior, since we only want the super admin to create org.

The contributor page also works, which is fine.

Where did you encounter the U of A issue? Is this page?
<img width="812" alt="Screenshot 2022-12-09 at 3 06 30 PM" src="https://user-images.githubusercontent.com/92752107/206787607-a6949909-8f2c-48d5-9ff6-a88e4e9c8b16.png">

**Comment by pengyin-shan** [comment]
@isawil as I noted today at our service team meeting, I removed this version from uat because I need to test 3.1.0 migration. So if you want to test this again, let me know and I'll re-deploy this back to uat.

**Comment by shilowil** [comment]
Hi Wendy -- sorry for this delay! Following up on this now. If it doesn't interfere with the 3.1.0 migration, could you re-deploy to UAT?

**Comment by pengyin-shan** [comment]
> Hi Wendy -- sorry for this delay! Following up on this now. If it doesn't interfere with the 3.1.0 migration, could you re-deploy to UAT?

Sorry this version has been replaced by my 3.1.0 test..don't worry, once 3.1.0 is deployed I'll merge this change, and update you once it is ready for testing

**Comment by shilowil** [comment]
No worries! Thanks.

**Comment by pengyin-shan** [comment]
Close this issue. Applied changes to version 3.1.0.
