### ISSUE TITLE
Confirm the current timezone and idea of using server timezone (MST) for DMP Assistant

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#262]
Before merging the PR (https://github.com/DMPRoadmap/roadmap/pull/3239) to the main codebase, we need to confirm our current timezone and user-preferred time zone.

Hi @isawil , can you check what timezone DMP Assisant is currently using for actions (such as creating plan, update planing...)? I think it is UTC but I'd like your help confirming it.

If it is UTC, we are thinking to change it to the server timezone. For DMP Assisant it is MST. Will our users like it? Or they are ok with the current setting?

**Comment by pengyin-shan** [comment]
If we decide to process, please feel free to assign this ticket to the new developer.

**Comment by aaronskiba** [comment]
The `updated_at` value (`2024-06-18 19:39:35.641059`) is in UTC time.
![Screenshot from 2024-06-18 13-39-40](https://github.com/portagenetwork/roadmap/assets/71047780/d0d5c7e3-47e1-4a3b-bf21-31e54c5c2c23)
![Screenshot from 2024-06-18 13-40-26](https://github.com/portagenetwork/roadmap/assets/71047780/39629b52-ce42-43cd-8a1a-c90c097c926c)

**Comment by aaronskiba** [comment]
The PR relevant to this issue (https://github.com/DMPRoadmap/roadmap/pull/3239) ended up being closed rather than merged into DMPRoadmap. Thus, this issue can be closed.
