### ISSUE TITLE
Error when adding new organization

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#267]
I tried to add a new organization, but when I submitted the institution information, I got the error, "Nil location provided. Can't build URI."

![image](https://user-images.githubusercontent.com/30664432/203821639-90088687-3259-4f62-b1d3-6e5d3d989ae0.png)

**Comment by pengyin-shan** [comment]
I tested in both uat and production and I cannot duplicate the case. @isawil what's the institution information you are trying to input?

**Comment by shilowil** [comment]
The institution name is Cégep de la Gaspésie et des Îles -- not sure if it's caused by special characters. I'll try again.

**Comment by shilowil** [comment]
Tried again and got the same error.

**Comment by pengyin-shan** [comment]
@isawil I just created one in the production server. Is this what you need? If so you can just update logo and contact info.

**Comment by shilowil** [comment]
Thank you! I'm getting a logo resize error, but will resize the logo. Otherwise everything seems to be working normally. Thanks again!
