### ISSUE TITLE
Update French for Portage template for systematic reviews

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#269]
We need to update the French translation of the Portage template for systematic reviews. The translation should be ready by November 30; when I have it in hand, I'll update on translation.io.

**Comment by shilowil** [comment]
Hi @pengyin-shan -- we've received the translations and I'm currently updating them. Could you check the following tickets to see if the translations have been added correctly? Thank you!

https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=161fe6ed&query=The%20types%20of%20data%20you%20collect%20may%20include%3A%20literature

https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=85e5e476&query=Word%2C%20RTF%2C%20PDF%2C%20etc.%3A

https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=6362ee97&query=Suggested%20format%20-%20PDF%20full-texts%20of%20included%20studies%3A

https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=58d93d93&query=https%3A%2F%2Fresearchdata.library.ubc.ca%2Fplan%2Forganize-your-data%2F

**Comment by pengyin-shan** [comment]
@isawil I did a sync on UAT, and to me, the translations are there. However, please confirm also, since I'm not familiar with french..Is https://uat.library.ualberta.ca:3000/org_admin/templates/3687/phases/3715/edit includes _your edit and corresponding french translation_?

if this page doesn't reflect your edit to the template, can you add it and check if the french are there or not?

**Comment by shilowil** [comment]
@pengyin-shan Looking at it now, I'm seeing that the French translation has been updated but not the hyperlinks -- I'll go back and change those in translation.io, right?

**Comment by pengyin-shan** [comment]
> @pengyin-shan Looking at it now, I'm seeing that the French translation has been updated but not the hyperlinks -- I'll go back and change those in translation.io, right?

Do you mean the french translation still points to the wrong link while English is the correct version? Or English is wrong already?

**Comment by shilowil** [comment]
Now both English and French are pointing to the wrong link. English had previously pointed to the correct link after changing it on the production site (though the changes haven't been published).

**Comment by pengyin-shan** [comment]
Ok, I think for this time only, I'll go directly to the production server and update the translation there (i.e. on `dmp-assistant` translation.io), since you made updates there instead of on uat. 

We can check on production translation this time without too much concern because the template hasn't been published yet. @isawil the English version on production is the the fixed version right?

**Comment by shilowil** [comment]
Yep, the English version on production is the fixed version. Sorry about editing on the wrong site! I'll make edits on UAT moving forward.

**Comment by pengyin-shan** [comment]
> 

no worry! this time we are safe. we can start next time that we edit and test on `uat` first, then once we confirm the status on `uat`, we can copy (or re-perform) what we did to the production server. It will be the safest way to operate (and avoid inevitable crush lol).

I'll go to sync on production server.

**Comment by shilowil** [comment]
Sounds good! Thanks. :)

**Comment by pengyin-shan** [comment]
@isawil I just did a production server translation sync. Can you can if your changes and corresponding translations are there?

**Comment by shilowil** [comment]
Yup! The links work now. Thanks! I still have a few translations to add and will update when they've all been added on translation.io.

**Comment by pengyin-shan** [comment]
> Yup! The links work now. Thanks! I still have a few translations to add and will update when they've all been added on translation.io.

Ok cool!

**Comment by shilowil** [comment]
@pengyin-shan All the translations have been added to translation.io!

**Comment by pengyin-shan** [comment]
> @pengyin-shan All the translations have been added to translation.io!

I checked and seems that the automated translation.io syncing process that was built on our production server already picked up the translation. can you verify?

**Comment by shilowil** [comment]
It looks like the French is updated in editable text boxes, but not when viewing the text in the non-editable fields:
![image](https://user-images.githubusercontent.com/30664432/205156761-bb259795-8a43-4881-bcc1-0a3ae1d6cfd4.png)

 versus

![image](https://user-images.githubusercontent.com/30664432/205156895-15e1f8f1-bbaf-4148-aadf-6f3aa05f32a2.png)

I'm also seeing we need to update the translation for the template details section at the top of the page. I have this translation -- do you know where it lives on translation.io? I can go in and update it.

**Comment by pengyin-shan** [comment]
> It looks like the French is updated in editable text boxes, but not when viewing the text in the non-editable fields: ![image](https://user-images.githubusercontent.com/30664432/205156761-bb259795-8a43-4881-bcc1-0a3ae1d6cfd4.png)
> 
> versus
> 
> ![image](https://user-images.githubusercontent.com/30664432/205156895-15e1f8f1-bbaf-4148-aadf-6f3aa05f32a2.png)
> 
> I'm also seeing we need to update the translation for the template details section at the top of the page. I have this translation -- do you know where it lives on translation.io? I can go in and update it.

Is this the only part that has translation problem? I checked tranlsation.io and it seems this term (https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=3a032e46&query=What%20data%20you%20will%20be%20sharing) doesn't have a default translation. So you can upload one and try again.

For those that you *already uploaded* translation to translation.io already, are they being translated?

**Comment by pengyin-shan** [comment]
And what part you meant on the template details section that doesn't have a translation? You can list them here and I'll find translation.io parts.

**Comment by shilowil** [comment]
This segment is being intermittently translated: https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=76b765c9

It initially showed as untranslated. After that, I went into the editing screen for it and saw it translated on the edit page. After exiting the edit page, it showed as translated on the main page. However, I cleared my browser cache and tried again, and it showed as untranslated again. On translation.io, I tagged it as 100% match -- is there anything else I should do to indicate that it's translated?

**Comment by shilowil** [comment]
This is the segment I updated in translation.io -- is it the correct one? https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=78080be2&query=What%20data%20will%20you%20be%20sharing%20and%20in%20what%20form%3F%20(e.g.%20raw%2C%20processed%2C%20analyzed%2C%20final)

The template description is this part:
![image](https://user-images.githubusercontent.com/30664432/205161604-749f4627-a716-4bf0-96dc-c76919a387d5.png)
and
![image](https://user-images.githubusercontent.com/30664432/205161682-7b532755-145b-42b9-a7df-6345b2f52456.png)

**Comment by pengyin-shan** [comment]
> This segment is being intermittently translated: https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=76b765c9
> 
> It initially showed as untranslated. After that, I went into the editing screen for it and saw it translated on the edit page. After exiting the edit page, it showed as translated on the main page. However, I cleared my browser cache and tried again, and it showed as untranslated again. On translation.io, I tagged it as 100% match -- is there anything else I should do to indicate that it's translated?

You meant translation.io right? For *this item* only, I checked my side and I can see your translation. You should just fill in the bottom box (i.e. the translation area) and translation.io will take your translation.

**Comment by pengyin-shan** [comment]
> This is the segment I updated in translation.io -- is it the correct one? https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=78080be2&query=What%20data%20will%20you%20be%20sharing%20and%20in%20what%20form%3F%20(e.g.%20raw%2C%20processed%2C%20analyzed%2C%20final)
> 
> The template description is this part: ![image](https://user-images.githubusercontent.com/30664432/205161604-749f4627-a716-4bf0-96dc-c76919a387d5.png) and ![image](https://user-images.githubusercontent.com/30664432/205161682-7b532755-145b-42b9-a7df-6345b2f52456.png)

I also saw this, with only HTML tag be different (https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=39d66a69&query=What%20data%20will%20you%20be%20sharing%20and%20in%20what%20form%3F%20(e.g.%20raw%2C%20processed%2C%20analyzed%2C%20final), I just copied your answer to this one also.

**Comment by shilowil** [comment]
Thank you! When I open a link to a segment on translation.io, I see different versions/iterations of that segment on the left side of the page. Should I update the translation for all of the segments that appear on a page?

**Comment by pengyin-shan** [comment]
> Thank you! When I open a link to a segment on translation.io, I see different versions/iterations of that segment on the left side of the page. Should I update the translation for all of the segments that appear on a page?

So basically, the translation.io wants to identify both HTML code and the actual content. So as you can see, if the HTML code change (even a little bit and we cannot see the change from UI), translation.io want a different version.

For this template change, it is very special because we need to consider both before publishing (i.e. item in the editor) and after publishing. *Normally you should only see one or a few untranslated versions.*

In cases where you see many versions listed on the left panel:
1. If not too many items waiting for translation *and only the HTML tag looks different*, you can update all of them by keeping the HTML tag the same and updating the content part. For example: `<p>Quelle documentation sera requise pour que les données soient lues et interprétées correctement dans le futur?</p>` and `<div class="display-readonly-textarea-content">Quelles données partagerez-vous et sous quelle forme (p. ex., données brutes, traitées, analysées, finales)?</div>` just have different html tag, so you can update both at the same time without asking for extra translation for translator.
2. **If you see lots of updates waiting or you just feel confused, give me the translation and I'll do the update. I'll do it and let you verify the result**.

**Comment by shilowil** [comment]
Thank you for clarifying! I'll go in and update these now.

**Comment by shilowil** [comment]
Listing tickets below:

dmp-assistant-test:

1.https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=161fe6ed&query=The%20types%20of%20data%20you%20collect%20may%20include%3A%20literature
2. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=85e5e476&query=Word%2C%20RTF%2C%20PDF%2C%20etc.%3A
3. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=6362ee97&query=Suggested%20format%20-%20PDF%20full-texts%20of%20included%20studies%3A
4. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=58d93d93&query=https%3A%2F%2Fresearchdata.library.ubc.ca%2Fplan%2Forganize-your-data%2F
5. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=f9888b50&query=What%20documentation%20will%20be%20needed%20for%20the%20data%20to%20be%20read%20and%20interpreted%20correctly%20in%20the%20future%3F
6. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=350678a1&query=https%3A%2F%2Flibguides.ucalgary.ca%2FDMPforSR%2Fmetadata
7. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=ef35e537&query=Where%20will%20you%20deposit%20your%20data%20for%20long-term%20preservation%20and%20sharing%20at%20the%20end%20of%20your%20research%20project%3F
8. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=39ba49f2&query=https%3A%2F%2Flibguides.ucalgary.ca%2FDMPforSR%2Fpreservation
9. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=78080be2&query=What%20data%20will%20you%20be%20sharing%20and%20in%20what%20form%3F%20(e.g.%20raw%2C%20processed%2C%20analyzed%2C%20final).
10.https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=161fe6ed&query=https%3A%2F%2Flibguides.ucalgary.ca%2FDMPforSR%2Fsharing
11. https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=76b765c9&query=are%20directly%20obtained%20from%20the%20instrument%2C%20simulation%20or%20survey.%C2%A0

dmp-assistant:

1. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=6058cb1c&query=The%20types%20of%20data%20you%20collect%20may%20include%3A%20literatur
2. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=305d0c13&query=Word%2C%20RTF%2C%20PDF%2C%20etc.%3A
3. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=85e5e476&query=Word%2C%20RTF%2C%20PDF%2C%20etc.%3A
4. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=6362ee97&query=Suggested%20format%20-%20PDF%20full-texts%20of%20included%20studies%3A
5. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=58d93d93&query=https%3A%2F%2Fresearchdata.library.ubc.ca%2Fplan%2Forganize-your-data%2F
6. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=f9888b50&query=What%20documentation%20will%20be%20needed%20for%20the%20data%20to%20be%20read%20and%20interpreted%20correctly%20in%20the%20future%3F
7. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=350678a1&query=https%3A%2F%2Flibguides.ucalgary.ca%2FDMPforSR%2Fmetadata
8. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=ef35e537&query=Where%20will%20you%20deposit%20your%20data%20for%20long-term%20preservation%20and%20sharing%20at%20the%20end%20of%20your%20research%20project%3F
9. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=39ba49f2&query=https%3A%2F%2Flibguides.ucalgary.ca%2FDMPforSR%2Fpreservation
10. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=78080be2&query=What%20data%20will%20you%20be%20sharing%20and%20in%20what%20form%3F%20(e.g.%20raw%2C%20processed%2C%20analyzed%2C%20final).
11. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=8db6b454&query=https%3A%2F%2Flibguides.ucalgary.ca%2FDMPforSR%2Fsharing
12. https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=76b765c9&query=are%20directly%20obtained%20from%20the%20instrument%2C%20simulation%20or%20survey.%C2%A0

**Comment by shilowil** [comment]
I'm encountering the same problem from before: when I look at the French version, it appears untranslated until I refresh. Once I refresh the page, it appears translated. An example:

[This segment](https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=77f1e6a7&query=The%20types%20of%20data%20you%20collect%20may%20include%3A%20literatur) appears translated in translation.io, but when I initially navigate to the template, it appears like this:

![image](https://user-images.githubusercontent.com/30664432/205338074-2c4d7053-68ff-4564-a819-0804b246a7d5.png)

After I refresh, it appears like this:

![image](https://user-images.githubusercontent.com/30664432/205338178-a5437e97-48fc-49ac-91f8-c4a6572cff37.png)

**Comment by pengyin-shan** [comment]
@isawil don't worry. In this case I can verify for you (my browser seems still ok). I opened Portage Template for Systematic Reviews, and choose French. Then I look through each question and found only the following that still needs to be translated:

1) https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=c53bf7ed&query=This%20template%20provides%20general%20guidance%20for%20those%20who%20are%20undertaking%20systematic%20reviews.%20It%20is%20suggested%20that%20different%20team%20members%20contribute%20to%20the%20DMP%20based%20on%20the%20stage%20of%20the%20review%20process%20in%20which%20they%20will%20be%20involved%20in%20creating%20data. (two of them)
2)https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=c53bf7ed&query=For%20additional%20guidance%20and%20examples%2C%20please%20see%20the%20online%20research%20guide%20located%20at (two of them)
3) https://translation.io/ualbertalib/dmp-assistant/en-CA?segment=c53bf7ed&query=is%20a%20tool%20that%20may%20help%20with%20planning%20and%20describing%20your (three)

And here is the screenshot for the full systematic review page on my browser, you can check it:
![AwesomeScreenshot-assistant-portagenetwork-ca-org_admin-templates-3738-phases-3770-edit-2022-12-02_11_31_part2](https://user-images.githubusercontent.com/92752107/205340147-f77f42b8-2ed8-4127-9c03-140a66c55811.png)
![AwesomeScreenshot-assistant-portagenetwork-ca-org_admin-templates-3738-phases-3770-edit-2022-12-02_11_31_part1](https://user-images.githubusercontent.com/92752107/205340152-e39ac576-43c9-46a8-8d40-ba2d595c12fd.png)

**Comment by pengyin-shan** [comment]
@isawil for your browser issue, have you tried on other browsers on your machine? How about reinstalling the browser or opening a new incognito window to see if it gets fixed? I feel it might have something to do with the cache setting of the browser.

**Comment by shilowil** [comment]
Thank you for checking! I've updated the segments you sent. Could you sync them and let me know if all looks okay? After confirmation, can we publish these changes?

**Comment by pengyin-shan** [comment]
> Thank you for checking! I've updated the segments you sent. Could you sync them and let me know if all looks okay? After confirmation, can we publish these changes?

I updated many times and noticed that seems translations are not synced for this part. Will investigate.

**Comment by shilowil** [comment]
Thank you for investigating! I wonder what it is.

**Comment by pengyin-shan** [comment]
> Thank you for investigating! I wonder what it is.

Updates so far: I verified that https://uat.library.ualberta.ca:3000/org_admin/templates/3687/edit on uat is working, **We only need FR only translation** (like https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=e2aa7714&query=This%20template%20provides%20general%20guidance%20for%20those%20who%20are%20undertaking%20systematic%20reviews.%20It%20is%20suggested%20that%20different%20team%20members%20contribute%20to%20the%20DMP%20based%20on%20the%20stage%20of%20the%20review%20process%20in%20which%20they%20will%20be%20involved%20in%20creating%20data.).

However, production server seems still not working. Then I confirmed that yes we have `dmp-assistant` all translated there. So I'm currently communicating with our system admin to see if our backend service (to pick up translation.io result and re-start httpd process to reflect it) is having problem. Will update here.

**Comment by pengyin-shan** [comment]
@isawil so I asked the system admin to manually re-trigger the translation process and it seems the french translation is picked up now.

Can you pls double-check *both English and French* on the production server last time to make sure both are correct? After you can publish the template, then try the French version again. Let me know if you see any problems with this feature.

**Comment by shilowil** [comment]
The English and French appear to be correct on the production site, both before and after publication. I'll let you know if I run into any more issues. Thank you for your help with this!
