### ISSUE TITLE
Centre hospitalier de l’Université de Montréal not showing as institution

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#272]
We've received reports that the Centre hospitalier de l’Université de Montréal organization is experiencing multiple errors. Users say that the organizational administrator is not able to access administrative privileges, and that the organization does not show in the "Indicate the primary research organization" field. 

In the production site, from the superadmin view, Centre hospitalier de l’Université de Montréal shows as an organization, with the correct organizational admin listed. However, when I do a user search for the admin, they are not listed as having admin privileges. I assigned them admin privileges when creating the organization, but de-selected the API privileges. They should have all other privileges, however.

**Comment by pengyin-shan** [comment]
> We've received reports that the Centre hospitalier de l’Université de Montréal organization is experiencing multiple errors. Users say that the organizational administrator is not able to access administrative privileges, and that the organization does not show in the "Indicate the primary research organization" field.
> 
> In the production site, from the superadmin view, Centre hospitalier de l’Université de Montréal shows as an organization, with the correct organizational admin listed. However, when I do a user search for the admin, they are not listed as having admin privileges. I assigned them admin privileges when creating the organization, but de-selected the API privileges. They should have all other privileges, however.

Adding admin in the 'organization' page does not automatically give admin user administrative privileges. Can you go to user page, use the 'Organizational admin privilege' checkbox (with API also checked) and see if the admin button comes back? Who is the admin?

**Comment by shilowil** [comment]
I think I've fixed it -- somehow, the organization became unmanaged. I re-added the administrator and changed it to a managed organization and now it's appearing in results. Waiting on user to see if their admin privileges have been restored.

**Comment by shilowil** [comment]
Adding that organizational admin privileges are now showing on my end. I think this is fixed, but let's wait on the users to confirm that it works on their end, too.

**Comment by pengyin-shan** [comment]
Sounds good. Just fyi the organizational admin user should get all privileges, including API one. Just check the 'Organizational Privledge' checkbox and you should be good to go.

**Comment by shilowil** [comment]
Thanks! I'll add the API privileges in the future. Just got confirmation from users that it's all working now, so I'll close the ticket.
