### ISSUE TITLE
Allow different contributor affiliations per plan

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#273]
A user noted that they are unable to set different affiliations according to contributors while creating a DMP (though they are able to change this after the plan has been exported). For example, they are unable to set contributor affiliations where Contributor 1 is affiliated with X Institution and Contributor 2 is affiliated with Y Institution.

Another user notes that when they try to change the affiliation of contributors, they get an error message stating that "The name you entered was not one of the suggestions listed," but that the problem is fixed when the plan is saved.

These questions came in from a listserv I'm not on, so I can't follow up with users directly... But I wanted to flag it.

**Comment by pengyin-shan** [comment]
#260 could link to this issue. Noticed 3.1.0 release (i.e. use the main codebase version of auto-fill) also fixed this issue. Will continue to navigate.

**Comment by shilowil** [comment]
Thanks, Wendy!

**Comment by pengyin-shan** [comment]
Close this ticket since now the contributor can have multiple affiliations in 3.1.0. Note contributor's affiliations won't display in the downloaded file
