### ISSUE TITLE
Administrator unable to access Guidance page

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#303]
An administrator is reporting that when they try to access Guidance, they are redirected to the dashboard and receive an error stating "Validation failed: name must be unique." 

I have double-checked that they have org admin privileges.

**Comment by pengyin-shan** [comment]
I need more detail: what do you mean by access Guidance? Did they use the Guidance function or edit Guidance in the template? What text did they try to put?

**Comment by pengyin-shan** [comment]
@isawil is this problem still be there? If I don't have time to deal with this ticket, you can re-assign this one to Omar

**Comment by pengyin-shan** [comment]
I won't have time to work on this unfortunately, but pls feel free to continue the navigation with the new developer.

**Comment by aaronskiba** [comment]
There unfortunately isn't enough information here for me to reproduce this bug. For instance, which user/org was affected? Did it occur when they clicked the "Guidance" button to navigate to `/org/admin/guidance/:id/admin_index`?

I will close the issue for now, but will definitely re-investigate it if the bug re-appears.
