### ISSUE TITLE
Logo from dragonfly folder is not matching logo names

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#327]
#326 link to this behavior. @isawil noticed that updating organizational detail will see the 500 error, but if clicking the back button, the info is saved successfully.

Cannot duplicate the same issue on UAT, and since UAT and production are sharing the same version of code. I assume the problem might come from the missing logo.

------
The `dragonfly` folder's logo images do not match `logo_uid` and `log_name` in `orgs` table in database. Need to check with Neil to *get correct logo files*, then manually add logo back

**Comment by pengyin-shan** [comment]
Unfortunately, I won't have time to work on this issue. @nmacgreg and @lagoan, so far what we found is that 1) some logos are missing from the server 2) the `logo_uid` field in `orgs` table in database does not match the current file physical address. Neil can ask for a backup from central IT to see if we can recover any logo files. 

Once you finish the navigation, please let Shiloh know so she can manually upload the logo back and ask the org admins to re-upload any missing logo.

**Comment by lagoan** [comment]
Related to #354

**Comment by 200455939-yashu** [comment]
@isawil   On any issues with the logo. It will request to update the logo before any updates to the organisation.
