### ISSUE TITLE
Rebranding - Summary

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#331]
@isawil , the Alliance team discussed rebranding DMP Assisant, including tasks such as changing the page style to adopt a new color theme and new logo, changing the 'support@portage' email address, changing the current URL, etc. This project got interrupted because of the 3.1.0 migration. You can pick it up in the future. I have built https://portagenetwork.github.io/ for anyone to taste the new style.

I have finished rebranding dev work based on the 3.0.4 version of DMP Assistant, at the `rebranding` branch (https://github.com/portagenetwork/roadmap/tree/rebranding) before 3.1.0 upgrade, thus **this branch** needs to migrate 3.1.0 changes before continuing. I understand that the re-upgrade could be tough, so I'll let the future developer decide if it should be totally redone. 

Lee used to send me the new branding style guide and image/logo files. I attached it here:
[DMP-PGD_LOGO_FILES.zip](https://github.com/portagenetwork/roadmap/files/10863395/DMP-PGD_LOGO_FILES.zip)
[DMP-PGD_brand_guide_v1.2.pdf](https://github.com/portagenetwork/roadmap/files/10863397/DMP-PGD_brand_guide_v1.2.pdf)
I'll also forward the email to you.

For your reference, these are the tickets we have created for re-branding:
- [x] #297 
- [x] #270 
- [x] #197 
- [x] #152
- [ ] #291 
I suggested you confirm their status at the service team meeting before the process. If you have any questions about rebranding, you can consult Lee and Omar.

**Comment by lagoan** [comment]
This work is looking great. I like the Digital-GREY re-branding better.

Here are a couple of things that we need to address:

- The link colour of #00DBA7 over #FFF needs to change so we can have higher contrast. At this point, however, I don't know what colour we can use.
- On the dropdown menu for organization selection the text colour is white with a white background. A darker font colour will work best:
![image](https://github.com/portagenetwork/roadmap/assets/1537909/a5386211-6a4e-4e12-936b-97a76eddcf41)
- The "Write plan" button on the plan creation tabs is out of place. This may be a change from upstream though: 
![image](https://github.com/portagenetwork/roadmap/assets/1537909/72fe9ee5-5813-4087-8ca2-3fbcd6bc3573)
- In each plan section the "Save" button has an animation. This is a great way to attract a user's attention for something that requires immediate attention, but it is not necessary for this "Save" button.
![image](https://github.com/portagenetwork/roadmap/assets/1537909/7b7cbf5d-ca6e-4edd-999c-5cda75fb8bfd)

**Comment by 200455939-yashu** [comment]
Click on '_My Dashboard_' then click on any other tabs quickly back and forth. The blue text colour shows up.

<img width="709" alt="Screenshot 2023-08-17 at 4 53 27 PM" src="https://github.com/portagenetwork/roadmap/assets/79508991/9a9d49b7-43bb-43f2-9f3f-f0941b8cb755">

**Comment by lagoan** [comment]
The drop down menu for selecting language is too far apart from the Language button:

![image](https://github.com/portagenetwork/roadmap/assets/1537909/b2902fb6-af4d-4c35-a83c-73e89a600ea3)

We get the same error for the profile dropdown menu:

![image](https://github.com/portagenetwork/roadmap/assets/1537909/f55e04ce-4263-403c-b52f-9291bc684d6f)

**Comment by shilowil** [comment]
The new link color looks much better, but we should check to ensure it still meets contrast requirements. FRDR uses a blue/green color for their links, but it is much darker -- [linking](https://www.frdr-dfdr.ca/repo/) so you can take a look and see if it might be suitable, but I like the yellow as well. 

![image](https://github.com/portagenetwork/roadmap/assets/30664432/74c8f4f3-8294-413c-b81e-ae9d8c1a1e8a)

I'd also like to see the DMP Assistant logo in the heading spaced similarly to the logo we have in the current design -- so, brought in towards the right a bit. In my browser (Firefox) it's showing at the far left of the screen.

**Comment by shilowil** [comment]
![image](https://github.com/portagenetwork/roadmap/assets/30664432/7efe8ad4-b85f-44c6-8de2-35972c10245f)

The "Notice: signed in successfully." alert is displaying in blue. Wondering if it's possible to update these colors as well? 

![image](https://github.com/portagenetwork/roadmap/assets/30664432/86423688-d9cb-43f2-8595-a16ecb5866f4)

Also noticing that the "Privacy statement" footer link isn't underlined while the other links are. The link still works, but it'd be best to underline it to bring it into cohesion with the other links.

**Comment by lagoan** [comment]
@200455939-yashu to change links to blue and yellow on hover as in **https://www.frdr-dfdr.ca/repo/**

**Comment by lagoan** [comment]
I found the logo for DMP Assistant has a large border on mouse hover. 

![image](https://github.com/portagenetwork/roadmap/assets/1537909/ad6b37d5-ca08-4aa8-bcdc-25f0292cab6c)

The current production version also has a hover border but it is not as large.

![image](https://github.com/portagenetwork/roadmap/assets/1537909/291493c3-362f-4ea9-9491-ceaf4ad0a6c1)

The organization header overlaps the DMP Assistant logo border as shown here:

![image](https://github.com/portagenetwork/roadmap/assets/1537909/5298d5c0-cac8-4505-b502-9a786cf92678)

@isawil @200455939-yashu Should we decrease the size of the border? What other actions can we take to change this?

**Comment by 200455939-yashu** [comment]
These borders needs to be reduced.

**Comment by closenma** [comment]
I'll be taking over this ticket to complete the remaining work on the rebrand over the next few weeks

**Comment by closenma** [comment]
We've completed all work except the final parts of email migration (where we're sending email from). Closing this issue and leaving #270 open and scheduling work for next cycle
