### ISSUE TITLE
Bug in plans where some cannot be updated

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#333]
Plans where the funder name has spaces fail to save.

**Comment by shilowil** [comment]
Reopening issue because errors are still being reported

**Comment by pgwillia** [comment]
![image](https://user-images.githubusercontent.com/1220762/232147984-327db7a2-5b49-44b2-84c8-61c74f4f34ca.png)

This error normally appears when two users are working on the same plan and the updates don't sync, or when a single user is working on the same plan in multiple tabs, but this message has been appearing even after users have logged out and logged back in again.

**Comment by lagoan** [comment]
@200455939-yashu For this one we want to check the behaviour on roadmap 4.

We will also want to figure out the process indicated on the error message of combining changes.

**Comment by aaronskiba** [comment]
I believe https://github.com/portagenetwork/roadmap/issues/525 documents this error. Rails 6 (part of `4.0.2+portage-4.0.0`) appears to be able to handle this former issue successfully.
