### ISSUE TITLE
Users cannot download public templates unless logged in

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#335]
Users are currently unable to download public templates unless they are logged in. If they try, they get this error:

![image](https://user-images.githubusercontent.com/30664432/228603020-fc216f08-dabd-4b50-a4bb-4909f490e5a3.png)

This happens for both PDF and Word downloads. Public DMPs are unaffected.

**Comment by aaronskiba** [comment]
Inside **public_pages_controller.rb**:
```ruby
  def template_export
    # only export live templates, id passed is family_id
    @template = Template.live(params[:id])
    # covers authorization for this action.
    # Pundit dosent support passing objects into scoped policies
    unless PublicPagePolicy.new(current_user, @template).template_export?
      msg = 'You are not authorized to export that template'
      redirect_to public_templates_path, notice: msg and return
      # raise Pundit::NotAuthorizedError
    end
```

Inside `class PublicPagePolicy` of **public_page_policy.rb**:
```ruby
  def template_export?
    @user.present? && @record.published?
  end
```

**@user.present?** is false whenever a user isn't signed in.

**Comment by aaronskiba** [comment]
It looks like the variable was incorrectly re-assigned during a previous commit: https://github.com/portagenetwork/roadmap/commit/268050aa08735249862e5a527927395322b93555

**Comment by aaronskiba** [comment]
This implementation doesn't use the Service described in this issue: https://github.com/portagenetwork/roadmap/issues/390

However, it may be a cleaner approach.
