### ISSUE TITLE
Password reset email shows incorrect support email address

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#338]
Password reset email currently reads as follows:

> Hello [user email address]
Someone has requested a link to change your DMP Assistant password. You can do this through the link below. 
[Change my password](https://assistant.portagenetwork.ca/users/password/edit?reset_password_token=z7h5vHTUPGxuPDxSVq-H)
If you didn't request this, please ignore this email.
All the best 
The DMP Assistant team 
Please do not reply to this email. If you have any questions or need help, please contact us at [support@portage.org](mailto:support@portage.org?subject=Query%20or%20feedback%20related%20to%20DMP%20Assistant) or visit https://assistant.portagenetwork.ca/contact-us

We should change the email address to support@portagenetwork.ca, pending the transition to the new support email address. I am also proposing that we change the email copy (it reads a little like spam) and add a French translation. I can take care of these last two items, but will need a developer to make the updates.

**Comment by shilowil** [comment]
New password reset email copy is as follows:

Hello [user email address],

Someone has requested a link to change your DMP Assistant password. You can do this through the link below:

[password reset link]

If you did not request a password change, please disregard this email. 

Thank you,
The DMP Assistant Team

Please do not reply to this email. If you have questions or need help, please contact us at support@portagenetwork.ca or visit https://assistant.portagenetwork.ca/contact-us.

**Comment by lagoan** [comment]
We can definitely make this change. 

I just want to note something, we modified the behaviour of the email used to send these messages so that a user could respond to these emails if they need support.

We could remove that part from the copy:

```
Hello [user email address],

Someone has requested a link to change your DMP Assistant password. You can do this through the link below:

[password reset link]

If you did not request a password change, please disregard this email.

Thank you,
The DMP Assistant Team

If you have questions or need help, please contact us at [support@portagenetwork.ca](mailto:support@portagenetwork.ca) or visit https://assistant.portagenetwork.ca/contact-us.
```

Let me know what you think @isawil
