### ISSUE TITLE
Remove broken links to Portage Network pages

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#339]
There are several broken links to old Portage Network pages that we should remove as part of rebranding. These include:

[Homepage](https://assistant.portagenetwork.ca/) (when logged out):
- Portage Network Training Resources ([link](https://portagenetwork.ca/tools-and-resources/training-resources/)) (we could redirect this to Alliance training resources when we have a training portal)
- University of California Curation Center (UC3) ([link](https://assistant.portagenetwork.ca/%20https://cdlib.org/services/uc3/)) (this is a mistyped link -- let's replace with [this link](https://cdlib.org/services/uc3/))

[About Us](https://assistant.portagenetwork.ca/about_us):
- Please contact your local institution ([link](https://portagenetwork.ca/tools-and-resources/institutional-rdm-contacts/)) (linked twice on this page)

[Help](https://assistant.portagenetwork.ca/help):
- Contacts at your institution ([link](https://portagenetwork.ca/tools-and-resources/institutional-rdm-contacts/))

I'll add more links as they are identified. This task is currently unassigned and will be assigned to new developers as they are onboarded.

**Comment by 200455939-yashu** [comment]
@isawil Can you please provide the links for the Help and About Us? And the link to "Portage Network Training " is not yet available.

**Comment by shilowil** [comment]
@200455939-yashu for the links to training resources, please use this link: https://alliancecan.ca/en/services/research-data-management/learning-and-training/training-resources

And for contacts at your local institution, please use this link: https://alliancecan.ca/en/services/research-data-management/learning-and-training/institutional-contacts

Thanks, and apologies for not including them on the original ticket!
