### ISSUE TITLE
Fix broken Terms and Conditions link in "Create account"

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#344]
On the homepage, in the "Create account" tab, the link to our Terms and Conditions is broken and pointing at https://portagenetwork.ca/tools-and-resources/dmp-assistant/dmp-assistant-terms-of-use/. It should be pointing to https://assistant.portagenetwork.ca/terms.

![image](https://github.com/portagenetwork/roadmap/assets/30664432/58c236ba-1876-4f83-8966-1f8379e41ddc)

**Comment by aaronskiba** [comment]
NOTE: Although this issue is closed, we are still requiring a French translation of the terms & conditions page. (Issue https://github.com/portagenetwork/roadmap/issues/388)
