### ISSUE TITLE
Unable to connect ORCiD account

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#345]
User is reporting an error when attempting to connect their ORCiD account to their profile. They have tried several times over the last week and continue to run into the error. I tried to connect and also received the same error. The error reads:

![image](https://github.com/portagenetwork/roadmap/assets/30664432/48f21a7f-a5df-4057-b448-5826b82f5d65)

**Comment by lagoan** [comment]
@isawil Could you list steps I can follow to recreate this bug? 

I linked my account to ORCID and did not find this error.

**Comment by lagoan** [comment]
The problem was the API account was locked because the user account was that from an organization. 

We requested the account to be unlocked and updated the account's name to that of a human being 🧑‍🦱 .

Now the requirements are met and it works.
