### ISSUE TITLE
DMP export issue

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#346]
We received the following bug report:

We are trying to export a DMP and transfer it into a google doc to add in comments. This is for the last exemplar that we have been working on. When we export it as text or pdf the whole of the response is there, however when it is exported as word (docx) file, half of the responses to the questions are missing. I think wherever there is a line gap it takes that as the end of text.

**Comment by aaronskiba** [comment]
Sorry, I referenced this issue by mistake, please disregard.

**Comment by 200455939-yashu** [comment]
@isawil This issue is not reproducible.
