### ISSUE TITLE
500 error when updating org details

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#354]
I'm running into a 500 error page when updating org details. (I can name the specific organization over Slack!)

I'm trying to update the admin email for an organization. The organization is managed but the admin email, admin name and URL are all showing as blank. When I add these details and try to save, I get the following page:

![image](https://github.com/portagenetwork/roadmap/assets/30664432/25f4efcb-d163-432c-a81c-95b0b8d03cc6)

@lagoan -- tagging you to triage to developers!

**Comment by 200455939-yashu** [comment]
Reference to the [327](https://github.com/portagenetwork/roadmap/issues/327)
