### ISSUE TITLE
Terms page does not show french language version

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#357]
**Expected behaviour:**

When navigating to the [terms of use page](https://assistant.portagenetwork.ca/terms) and the UI is set to show the French language, the content should be in French.

**Actual behaviour:**

The content for the terms of use page is shown in English.

**Steps to reproduce:**

1. Go to the application
2. Set language to French
3. Go to  [terms of use page](https://assistant.portagenetwork.ca/terms)

There are a couple of reasons why this can be happening:

1. The translation is not up to date on translation.io (We will go over the process of updating translations)
2. The locale check is causing problems. Could be related to #355

**Comment by 200455939-yashu** [comment]
@isawil Can you please provide a French link for the [terms of use page](https://assistant.portagenetwork.ca/terms)

**Comment by 200455939-yashu** [comment]
@isawil  As discussed, For [terms of use page](https://assistant.portagenetwork.ca/terms) are displaying in English on the French version of the site. This will need to be investigated to find a cause, but we will use the existing link in this release for consistency until we find a solution.
