### ISSUE TITLE
Comment can only be edited once

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#37]
From a user in beta test:

The first comment I added and saved worked well. When I clicked on "Edit" under the comment, I was able to edit it, but when I clicked saved, nothing happened. I clicked save a couple of times, and nothing happend. I went to another section and entered a comment and clicked save for that comment, and nothing happened either. So I moved away from the page (when to the project detail tab) and came back, and the edit had been accepted and the new comment in another section had also been accepted. Then I tried to remove a comment. After I clicked "remove", it asked if I was sure I wanted to remove. I clicked the "Remove" button and nothing happened. So again, I waited a couple of minutes (not moving away from the page) and the comment was finally removed.

**Comment by lagoan** [comment]
@pengyin-shan is this still and issue?

**Comment by pengyin-shan** [comment]
Not see the same error after the 3.0 release. close this issue for now
