### ISSUE TITLE
Error when upgrading to  font-awesome-sass v6.4.0

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#384]
The GitHub actions are failing for Dependabot pull request https://github.com/portagenetwork/roadmap/pull/372, and the following error is consistently encountered:

```
SassC::SyntaxError at /plans
Error: File to import not found or unreadable: font-awesome-sprockets.
        on line 16:1 of app/assets/stylesheets/application.scss
>> @import "font-awesome-sprockets";
```

It appears that the `@import "font-awesome-sprockets"` is not required for v6:
https://fontawesome.com/v6/docs/web/use-with/ruby-on-rails#import-font-awesome

**Comment by aaronskiba** [comment]
According to the upstream CHANGELOG.md, we may want to remove the font-awesome-sass gem entirely and replace it with its corresponding npm package. This change is handled in release v4.1.0: https://github.com/DMPRoadmap/roadmap/blob/main/CHANGELOG.md#removed-webpacker-gem

```
Removed font-awesome-sass gem and used @fortawesome/fontawesome-free npm package
Issue with @import 'font-awesome-sprockets'; line in app/assets/stylesheets/application.scss. Removed that line after referring to the latest font-awesome install/setup guide which no longer includes it.
```

**Comment by lagoan** [comment]
This problem will be fixed after our upgrade to v4
