### ISSUE TITLE
Additional broken links to Portage Network pages

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#385]
Like issue https://github.com/portagenetwork/roadmap/issues/339, there are several broken links to old Portage Network pages that we should remove as part of rebranding.

All of the following listed links are currently redirecting to https://alliancecan.ca/en/services/research-data-management:

**contact us (French)** https://portagenetwork.ca/fr/contactez-nous/
**contact us (English)** https://portagenetwork.ca/contact-us/

**how to manage your data (French)** https://portagenetwork.ca/fr/outils-et-ressources/assistant-pgd/comment-gerer-vos-donnees/
**how to manage your data (English)** https://portagenetwork.ca/tools-and-resources/dmp-assistant/how-to-manage-your-data/

**terms of use (French)** https://portagenetwork.ca/fr/outils-et-ressources/assistant-pgd/conditions-dutilisation-de-lassistant-pgd/ (Also described in issue https://github.com/portagenetwork/roadmap/issues/357)
- **NOTE: terms of use (English)** is working https://assistant.portagenetwork.ca/terms

**Comment by 200455939-yashu** [comment]
@isawil Please provide the links for **Contact us** and **how to manage your data**

**Comment by lagoan** [comment]
@isawil to look for links in French from the Alliance.

**Comment by aaronskiba** [comment]
Note: When issue https://github.com/portagenetwork/roadmap/issues/388 is completed, both English & French translation of terms-of-use will be accessible from https://assistant.portagenetwork.ca/terms

**Comment by lagoan** [comment]
@isawil could you please take a look at missing web pages?
