### ISSUE TITLE
Missing French translation for Terms of Use and Privacy Policy pages

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#388]
The Terms of Use and Privacy Policy pages do not display in French when French is toggled as the language.

Terms of Use: https://assistant.portagenetwork.ca/terms
Privacy Policy: https://assistant.portagenetwork.ca/privacy

The Privacy Policy page title does display in French as a browser tab, but not on the page itself. I assume we had translations for these pages before, so they seem to be missing or otherwise not displaying. (The "Help" page does display in French.)

@lagoan -- tagging you to triage as needed!

**Comment by aaronskiba** [comment]
NOTE: `def terms_of_use_path` in application_helper.rb is temporarily hardcoded to always return English route. This will have to be changed again when the French terms-of-use route is made available.

**Comment by lagoan** [comment]
@aaronskiba will take a look at the missing translations and add them to translation.io

**Comment by aaronskiba** [comment]
Hi @isawil, here is a link to the terms-of-use text that is needing a French translation, thanks.

https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=e83a70d0

**Comment by aaronskiba** [comment]
Also, here is the privacy text needing a French translation, thank you.

https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=800754b1
