### ISSUE TITLE
Checks For UAT

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#398]
### #344 Fix broken Terms and Conditions link in "Create account"
- Until the French translation is available, both language choices should link to the English terms page.
### #327 Logo from dragonfly folder is not matching log names
- Missing logos no longer result in 500 error
### #346 DMP export issue
- Issue should be non-reproducible
### #335 Users cannot download public templates unless logged in

**Comment by shilowil** [comment]
#344 link is fixed and working

#339 links are fixed and working

#196 Unsure how to test -- UAT account isn't connected to an email address I have access to

#327 no longer resulting in 500 error

#346 issue is non-reproducible

#335 fixed -- can download public DMPs without being logged in
