### ISSUE TITLE
Webdrivers::NetworkError: For Github Actions Tests

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#403]
The following error has been repeatedly encountered while running GitHub Actions Tests:

```
 Failure/Error: browser = Capybara.current_session.driver.browser

     Webdrivers::VersionError:
       Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
     # ./spec/support/helpers/capybara_helper.rb:5:in `clear_cookies!'
     # ./spec/support/helpers/sessions_helper.rb:16:in `sign_in_as_user'
     # ./spec/features/modal_search_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Webdrivers::NetworkError:
     #   Net::HTTPServerException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
     #   ./spec/support/helpers/capybara_helper.rb:5:in `clear_cookies!'
```

This specific error has appeared in the logs of the following tests:
- Tests - PostgreSQL / postgresql (push)
- Tests - PostgreSQL / postgresql (pull_request)
- Tests - MySQL / mysql (push)
- Tests - MySQL / mysql (pull_request)
- Ruby / test (pull_request)

Example: https://github.com/portagenetwork/roadmap/actions/runs/5672424347/job/15372827022?pr=402

**Comment by aaronskiba** [comment]
Temp fix was implemented so that https://github.com/portagenetwork/roadmap/pull/402 could pass its tests: https://github.com/portagenetwork/roadmap/pull/402/commits/e9dac5189ed5fb447e26566a8e285ca17de04b0a

**Comment by lagoan** [comment]
We can check if this is still an issue when upgrading to version 4.

If the problem still exists on roadmap 4, we can try installing the required version on docker.

@pgwillia found this works for her

```
sudo apt install chromium-chromedriver
```
and then added export 

```
CHROMIUM_CHROMEDRIVER_PATH=/snap/bin/chromium.chromedriver to my ~/.bashrc
```

**Comment by pgwillia** [comment]
I found this in jupiter as well.  Here was the fix there https://github.com/ualbertalib/jupiter/commit/1bf0273cd890cd938a12bf1a45d6259a5e966298

**Comment by lagoan** [comment]
We adde a small patch to get us over the upgrade to ruby 3.
