### ISSUE TITLE
Repeated text in Getting started section of /about_us

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#407]
Related issue: https://github.com/portagenetwork/roadmap/issues/404

The below pictures depict how the following text is repeated in the "Getting started" section of https://assistant.portagenetwork.ca/about_us:

**ENGLISH**
- "If you do not have a DMP Assistant account, click on [Sign up](https://assistant.portagenetwork.ca/) on the homepage."
- "If you do not have a DMP Assistant account, click on ['Sign up' ](https://assistant.portagenetwork.ca/)on the homepage."
- "Please visit the [Help](https://assistant.portagenetwork.ca/help) page for guidance."
- "Please visit the ['Help' ](https://assistant.portagenetwork.ca/help_url)page for guidance."

**FRENCH**
- "If you do not have a Assistant PGD account, click on [Sign up](https://assistant.portagenetwork.ca/) on the homepage."
- "Si vous ne possédez pas de compte dans l'Assistant PGD, cliquez sur [« S'inscrire »](https://assistant.portagenetwork.ca/) dans la page d'accueil."
- "Please visit the [Aide](https://assistant.portagenetwork.ca/help) page for guidance."
- "Visitez la page [« Aide » ](https://assistant.portagenetwork.ca/help_url)pour consulter l'aide disponible."
<img width="745" alt="Screenshot 2023-07-28 at 11 49 01 AM" src="https://github.com/portagenetwork/roadmap/assets/71047780/9a63176a-78f3-4b18-b795-7d22b82eaea9">
<img width="1143" alt="Screenshot 2023-07-28 at 11 50 24 AM" src="https://github.com/portagenetwork/roadmap/assets/71047780/e31f0d9c-2cdc-44f1-b396-b8d9dd0d6042">

**Comment by lagoan** [comment]
@aaronskiba fixed this earlier.
