### ISSUE TITLE
Missing front end French translations (Part 2)

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#411]
This issue cites additional missing translations to those cited in #404.

## Research Outputs
- Several fields are untranslated (see screenshot)
<img width="1193" alt="Screenshot 2023-08-02 at 2 53 34 PM" src="https://github.com/portagenetwork/roadmap/assets/71047780/f22e9927-d014-444a-b9f3-25d3b187cd4d">

## Editing Notification
![Screenshot from 2023-09-18 12-14-02](https://github.com/portagenetwork/roadmap/assets/71047780/965a938d-6578-41e4-b630-7a8ca9aba4ba)

![Screenshot from 2023-09-18 12-47-23](https://github.com/portagenetwork/roadmap/assets/71047780/3963928a-98bb-4d9d-90b1-552d475e9a34)

![Screenshot from 2023-09-18 12-47-49](https://github.com/portagenetwork/roadmap/assets/71047780/8538bf8d-9379-404f-a282-2e365008f828)

![Screenshot from 2023-09-18 13-05-28](https://github.com/portagenetwork/roadmap/assets/71047780/2fbd9730-80ba-4c02-afd9-9e28dced8200)

![Screenshot from 2023-09-18 13-03-40](https://github.com/portagenetwork/roadmap/assets/71047780/da723061-d4d6-4c57-a6ac-741cbe27a76e)

![Screenshot from 2023-09-18 13-04-03](https://github.com/portagenetwork/roadmap/assets/71047780/d2adeda3-2f01-42b7-aa79-4b7563335d30)

![Screenshot from 2023-09-18 13-06-41](https://github.com/portagenetwork/roadmap/assets/71047780/a41be136-8298-4e40-9239-ad2458d95e8c)

**Comment by lagoan** [comment]
@aaronskiba could you please check if this is still missing after a translation update?

**Comment by aaronskiba** [comment]
```
Managed
Api Clients
Info
Warning
Danger
Google Analytics Tracker
Managed? (allows Org Admins to access the Admin menu)
None
Merge Organisations
Please select the Organisation that will replace the current organisation: '<strong>%{org_name}</strong>'.
Then click the 'analyze' button to review the proposed changes. Note that no changes will take place until you have reviewed and approve of the changes.
Analyze
Merging '%{from_org_name}' into '%{to_org_name}'
Summary:
Counts of '%{to_org_name}' records before and after a merge with %{from_org_name}.
Record Type
'%{to_org_name}' Count - before merge
'%{to_org_name}' Count - after merge
Details:
The table below shows the specific changes that will occur during the merge process. Once the merge is complete, '%{from_org_name}' will be deleted. You can then consolidate/correct any merge issues (e.g. remove any departments that were duplicated)
Warning: The changes proposed above will be committed to the database. '%{org_name}' will then be deleted.
These changes cannot be undone! Do not proceed unless you are certain.
You may find it helpful to make a note of the expected number of records for each category that will be merged before continuing.
Merge records
The following attributes will be updated
<p>The following %{object_types} will be moved over to '%{org_name}':</p>
```

Additional entries (added Sept. 27, 2023):
```
Successfully merged '%{org}' into '%{target_org}'.
Research Institute
Project
School
```

**Comment by aaronskiba** [comment]
This one is currently giving me a lot of grief. I think I will save it for after the upcoming 3.31 release:

![Screenshot from 2023-09-18 13-03-40](https://github.com/portagenetwork/roadmap/assets/71047780/91ddff84-1eb5-4b23-9c74-03c13b4188db)

**Comment by aaronskiba** [comment]
I shouldn't have closed this issue as completed. It looks likes maybe ALL of the translations are still missing from the `dmp-assistant` project.

However, several of the translations appear to exist within the `dmp-assistant-test` project. I will see which currently exist there. Also, I'll eventually combine this issue with the following newest translations issue: https://github.com/portagenetwork/roadmap/issues/698

**Comment by aaronskiba** [comment]
DMP-ASSISTANT-TEST
```
Managed <-> Géré

Managed? (allows Org Admins to access the Admin menu)
<->
Géré? (permet aux administrateurs de l'organisation d'accéder au menu Admin)
```

**Comment by aaronskiba** [comment]
The corresponding translations of these segments have been added to translation.io
