### ISSUE TITLE
Broken link to /help page

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#412]
Note: The duplicate "Sign Up" and "Help" messages are noted in issue #407

The bottom "Help" link is currently not working.
<img width="1165" alt="Screenshot 2023-08-02 at 3 16 26 PM" src="https://github.com/portagenetwork/roadmap/assets/71047780/e194d057-4089-41f2-aac9-f56d01f6502c">

<img width="1065" alt="Screenshot 2023-08-02 at 3 18 53 PM" src="https://github.com/portagenetwork/roadmap/assets/71047780/d02d60c6-d902-46d0-a7c1-bd91260200df">

**Comment by lagoan** [comment]
@aaronskiba updated copy text and was resolved at the same time.
