### ISSUE TITLE
New translation.io Entries For English/French Translators

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#413]
### This first list of words/phrases was taken from the translation.io history. Let me know if you'd like me to add **Missing** tags to them, or if anything else is required.
- <img width="314" alt="Screenshot 2023-08-04 at 10 42 52 AM" src="https://github.com/portagenetwork/roadmap/assets/71047780/e0362903-1b57-45be-beeb-5ae58cdfb034">

```
- Other Licenses - will load a complete list -
Metadata Standard
(e.g. DataCite, Dublin, Biological, etc.)
(e.g. DNA, titanium, FAIR, etc.)
Manage API access for external applications
Data paper
Interactive resource
Model representation
Physical object
Open
Embargoed
Restricted
Closed
Agriculture, Forestry, Horticulture and Veterinary Medicine
Biology
Chemistry
Computer Science, Electrical and System Engineering
Construction Engineering and Architecture
Geosciences (including Geography)
Humanities
Materials Science and Engineering
Mathematics
Mechanical and industrial Engineering
Medicine
Physics
Social and Behavioural Sciences
Thermal Engineering/Process Engineering
Economics and business
Health sciences
Natural sciences
Languages and literature
Materials engineering
History and archaeology
Social Sciences
Other humanities
Philosophy, ethics and religion
Law
Medical engineering
Art (arts, history of arts, performing arts, music)
Industrial Biotechnology
Chemical sciences
Agriculture, forestry, and fisheries
Other medical sciences
Agricultural biotechnology
Nano-technology
Environmental engineering
Electrical engineering, electronic engineering, information engineering
Chemical engineering
Agricultural Sciences
Animal and dairy science
Mechanical engineering
Sociology
Educational sciences
Other agricultural sciences
Social and economic geography
Medical and Health Sciences
Basic medicine
Clinical medicine
Other social sciences
Computer and information sciences
Civil engineering
Other natural sciences
Political science
Veterinary science
Health biotechnology
Psychology
Earth and related environmental sciences
Biological sciences
Other engineering and technologies
Media and communications
Physical sciences
Engineering and Technology
Environmental biotechnology
```

### In addition, this link should lead to all of the translation.io entries with a **Missing** tag: https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=782fe9db&tag_ids%5B%5D=1815

- NOTE: Out of all of the translation.io entries with a **Missing** tag, I believe this is the only one **not** provided by me (it shouldn't have to be sent to the translation team): https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=1bd4e418&tag_ids%5B%5D=1815

**Comment by aaronskiba** [comment]
Hi @isawil, I have some additional translations here:

```
If you do not have a %{application_name} account, click on
Sign up
on the homepage.
Please visit the
page for guidance.
```

**Comment by aaronskiba** [comment]
> Hi @isawil, I have some additional translations here:
> 
> ```
> If you do not have a %{application_name} account, click on
> Sign up
> on the homepage.
> Please visit the
> page for guidance.
> ```

Update: we discussed the repeated entries in the About Us section (https://github.com/portagenetwork/roadmap/issues/407). As a result, these particular translations will not be needed.

**Comment by shilowil** [comment]
All translations have been added to translation.io, minus the additional translations you noted will not be needed.

**Comment by lagoan** [comment]
@isawil to double-check changes and close ticket

**Comment by shilowil** [comment]
@lagoan -- I've sent these terms for translation. They will hopefully be translated within the next week, though I am awaiting confirmation on timeline. Noting the missing translations for the ToS and Privacy Policy pages, we can bundle these with those translations in a small release following the release we're hoping to cut this week.

**Comment by shilowil** [comment]
@lagoan @aaronskiba all are now translated and added to dmp-assistant
