### ISSUE TITLE
"Already Initialized Constant" Warnings

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#419]
The following warnings appear when executing `rails s`, `rails c`, `rspec`, and other commands:

```
/Users/aaronskiba/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/aaronskiba/.rvm/gems/ruby-2.7.6@v4.0.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/aaronskiba/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/Users/aaronskiba/.rvm/gems/ruby-2.7.6@v4.0.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/Users/aaronskiba/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/Users/aaronskiba/.rvm/gems/ruby-2.7.6@v4.0.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
```

- https://github.com/ruby/net-imap/issues/16#issuecomment-803086765 removed the warnings by adding gem "net-http" to Gemfile. However, this gem is absent from release v4.0.0, so maybe the warnings will be gone after the merge with release v4.0.0 is completed?

_Originally posted by @aaronskiba in https://github.com/portagenetwork/roadmap/issues/414#issuecomment-1671755767_

**Comment by aaronskiba** [comment]
I performed a quick test by setting `ruby '>= 3.0.5'` in Gemfile and then running `bundle install`. When I did this, the warnings disappeared. Since this upgrade is required for [release v4.1.0](https://github.com/DMPRoadmap/roadmap/releases/tag/v4.1.0), these warnings should eventually take care of themselves.

**Comment by lagoan** [comment]
@aaronskiba found these issues were fixed in upgrade.
