### ISSUE TITLE
Different 'Getting Started' Text For Signed In vs Non-Signed In

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#420]
The **Getting started** section of the **About Us** page includes the sentence, "_If you do not have a DMP Assistant account, click on Sign up on the homepage._" If the user is already signed in, the **Sign up** link reroutes to the  **Plans** page.

That sentence may not be necessary for a user that is currently signed in. It might be better to have this sentence only render when the user is not signed in.

<img width="645" alt="Screenshot 2023-08-16 at 9 12 07 AM" src="https://github.com/portagenetwork/roadmap/assets/71047780/4447c11e-7d63-415a-8a6e-392ee55f09d4">

What are your thoughts on this idea, @isawil? Thank you.

**Comment by shilowil** [comment]
@aaronskiba I agree -- we can get rid of this sentence for users who are already signed in.
