### ISSUE TITLE
"undefined" Text For Required Fields In Create Guidance

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#447]
On the 'Create Guidance' page, the rendered text currently reads as "undefined" on all of the red asterisks.

![Screenshot from 2023-09-18 11-20-19](https://github.com/portagenetwork/roadmap/assets/71047780/96c01a50-6dfa-48de-8c4b-f24e62df6f04)

**Comment by aaronskiba** [comment]
Note: this also exists within the Request feedback section of the Organization Details page.

**Comment by lagoan** [comment]
We can address this after the upgrade.

**Comment by aaronskiba** [comment]
Closing this issue because it is better documented in https://github.com/portagenetwork/roadmap/issues/552.
