### ISSUE TITLE
App not rendering in French after clicking dmp-pgd.ca/?locale=fr_CA link

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#455]
The /terms and /privacy pages include links such as [assistant.portagenetwork.ca](https://assistant.portagenetwork.ca/) / [assistant.portagenetwork.ca/?locale=fr_CA](https://assistant.portagenetwork.ca/?locale=fr_CA). However, both links result in the homepage still being rendered in English.

**Comment by lagoan** [comment]
This issue does not exist in production.

**Comment by aaronskiba** [comment]
This issue seems to exist with the [dmp-pgd.ca](https://dmp-pgd.ca/) / [dmp-pgd.ca/?locale=fr_CA](https://dmp-pgd.ca/?locale=fr_CA) links within the /terms and /privacy pages.

**Comment by aaronskiba** [comment]
Maybe we could simply replace all mentions of `dmp-pgd.ca / dmp-pgd.ca/?locale=fr_CA` with `dmp-pgd.ca`? That way the user would still be routed to the homepage and the language would match the language they had selected while viewing the privacy or terms page.

@shilowil, what are your thoughts on this? Do you think we should proceed with this proposed idea to address the English/French links that aren't switching the language?

**Comment by shilowil** [comment]
@aaronskiba your approach sounds good -- let's proceed with it!
