### ISSUE TITLE
Handle hardcoding of assistant.portagenetwork.ca and https://assistant.portagenetwork.ca/

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#456]
One of the rebranding changes is that the domain has been changed from `assistant.portagenetwork.ca` to `dmp-pgd.ca`.

There are several hardcoded entries of the strings `assistant.portagenetwork.ca` and `https://assistant.portagenetwork.ca/` within the codebase. We will need them to respectively be changed to `dmp-pgd.ca` and `https://dmp-pgd.ca/`.

However, both of the domains are currently accessible, so hardcoding won't work.

[Upstream release v4.0.0](https://github.com/DMPRoadmap/roadmap/releases/tag/v4.0.0) implements the ENV variable `DMPROADMAP_HOST` and assigns the hostname to it (e.g. `Rails.application.routes.default_url_options[:host] = ENV.fetch('DMPROADMAP_HOST', 'dmp-pgd.ca') `). Perhaps this is the best way to handle the `assistant.portagenetwork.ca` vs `dmp-pgd.ca` hostname?

**Comment by lagoan** [comment]
This will be hardcoded to minimize changes in codebase.
