### ISSUE TITLE
Portions of Portage Template for Research in History and the Humanities display in French when English is toggled

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#488]
In the browser version of the Portage Template for Research in History and the Humanities, two questions and their accompanying guidance display in French when English is toggled:

1. Décrire la stratégie de diffusion envisagée pour faire connaître l’existence du matériel de recherche auprès de ses publics. (Question 2, "Sharing and Reuse" section)
2. Des coûts sont-ils associés au choix du lieu de dépôt et à la préparation des données? (Question 3, Preservation). (As a note -- this question also recommends users contact the old support email, so we should consider updating it to reflect the new email.)

@lagoan -- tagging for you to triage as appropriate

**Comment by aaronskiba** [comment]
There appears to be other French fields in this template as well:
1. For the "Sharing and Reuse" section of phase 1, in addition to **Question 2,** **Example answer** and **Guidance** are also in French.
![Screenshot from 2023-10-25 15-41-04](https://github.com/portagenetwork/roadmap/assets/71047780/0b3b55a0-90c9-46bf-ba41-5fbbe84c0b6b)

2. For the "Preservation" section of phase 2, in addition to **Question 3**, **Guidance** is also in French.
![Screenshot from 2023-10-25 15-43-55](https://github.com/portagenetwork/roadmap/assets/71047780/b432070b-100f-4bbf-8902-ddc6f788e604)

**Comment by aaronskiba** [comment]
The English versions of this text may already exist on translation.io (please verify @isawil):

Phase 1, Sharing and Reuse Section, Question Text:
https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=0d2a9a27&query=D%26eacute%3Bcrire%20la%20strat%26eacute%3Bgie%20de%20diffusion%20envisag%26eacute%3Be%20pour%20faire%20conna%26icirc%3Btre%20l%26rsquo%3Bexistence%20du%20mat%26eacute%3Briel%20de%20recherche%20aupr%26egrave%3Bs%20de%20ses%20publics.

Phase 1, Sharing and Reuse Section, Example Answer:
https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=a3aa1954&query=%3Cstrong%3EExample%3A%20%3C%2Fstrong%3EReporting%20in%20a%20recognized%20data%20repository%2C

Phase 1, Sharing and Reuse Section, Guidance: (support@portagenetwork.ca will definitely need to be updated)
https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=f63ed01b&query=Pour%20optimiser%20la%20diffusion%20d

Phase 2, Preservation, Question Text:
https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=ac3eb1ee&query=Des%20co%26ucirc%3Bts%20sont-ils%20associ%26eacute%3Bs%20au%20choix%20du%20lieu

Phase 2, Preservation, Guidance: (support@portagenetwork.ca will definitely need to be updated)
https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=aed029ae&query=La%20pr%26eacute%3Bparation%20du%20mat%26eacute%3Briel

**Comment by aaronskiba** [comment]
Editing and re-publishing the template will create a new version of the template. As a result, existing plans that use this template will still see unwanted French text. 
If we wanted to correct the French text for existing templates, I think we'd have to edit these db entries.

**Comment by aaronskiba** [comment]
#### CHECKING WHAT IS CHANGED IN DB WHEN EDITING A QUESTION IN A TEMPLATE

#### BEFORE EDIT
`action="/org_admin/templates/3877/phases/3927/sections/24660/questions/75914"`
![Screenshot from 2023-10-25 09-44-26](https://github.com/portagenetwork/roadmap/assets/71047780/f09b573c-0e26-439e-8ae5-ffb39e67f026)

### EDIT
![Screenshot from 2023-10-25 09-45-03](https://github.com/portagenetwork/roadmap/assets/71047780/192beb93-ea6d-4a08-8dbd-cf618fbca2fc)

#### AFTER
`action="/org_admin/templates/3878/phases/3929/sections/24674/questions/75950"`
![Screenshot from 2023-10-25 09-46-34](https://github.com/portagenetwork/roadmap/assets/71047780/604e6d47-7b98-4c49-bbcc-2d4678cd4162)

- Editing the question saved a new Template to the db, new Sections to the db, and new Questions to the db.

**Comment by aaronskiba** [comment]
### Draft Script For Querying the db Fields Needing to Be Updated

```ruby
template_title = 'Portage Template for Research in History and the Humanities'
template_locale = 'en-CA'

sharing_and_reuse = 'Sharing and Reuse'
sharing_and_reuse_question_text = 'D&eacute;crire la strat&eacute;gie de diffusion envisag&eacute;e pour faire conna&icirc;tre l&rsquo;existence du mat&eacute;riel de recherche aupr&egrave;s de ses publics.'
sharing_and_reuse_example_answer = '<span style="font-weight: 400;"><strong>Exemple : </strong>Signalement dans un d&eacute;p&ocirc;t de donn&eacute;es de reconnu, attribution d&rsquo;un identifiant p&eacute;renne comme DOI - voir le </span><a href="https://zenodo.org/record/3862656/files/Dataset%20Identifiers%20Guide.pdf?download=1"><span style="font-weight: 400;">guide du projet FREYA</span></a><span style="font-weight: 400;"> (</span><em><span style="font-weight: 400;">lien en anglais</span></em><span style="font-weight: 400;">), signalement dans les listes de diffusion et r&eacute;seaux sociaux.</span>'
sharing_and_reuse_guidance = "<p><span style=\"font-weight: 400;\">Pour optimiser la diffusion du mat&eacute;riel de recherche, suivre le plus possible les principes FAIR. L&rsquo;</span><a href=\"https://ardc.edu.au/resources/working-with-data/fair-data/fair-self-assessment-tool/\"><span style=\"font-weight: 400;\">Australian Research Data Commons</span></a><span style=\"font-weight: 400;\"> offre un outil d&rsquo;&eacute;valuation du respect de ces principes qui est tr&egrave;s facile d'utilisation (</span><em><span style=\"font-weight: 400;\">lien en anglais</span></em><span style=\"font-weight: 400;\">). Le Digital Curation Centre fournit un </span><a href=\"http://www.dcc.ac.uk/resources/how-guides/cite-datasets\"><span style=\"font-weight: 400;\">guide d&eacute;taill&eacute; sur la citation des donn&eacute;es</span></a><span style=\"font-weight: 400;\"> (tant num&eacute;riques que physiques; </span><em><span style=\"font-weight: 400;\">lien en anglais</span></em><span style=\"font-weight: 400;\">).<br /><br />Pour rendre le mat&eacute;riel r&eacute;cup&eacute;rable par d&rsquo;autres outils et le citer dans les publications savantes, publication d&rsquo;un article de donn&eacute;es dans une revue en libre acc&egrave;s comme <a href=\"https://brill.com/rdj\">Research Data Journal for the Humanities and Social Sciences</a> (<em>lien en anglais</em>).</span></p>\r\n<p><span style=\"font-weight: 400;\">Consulter au besoin une </span><a href=\"https://portagenetwork.ca/fr/outils-et-ressources/personnes-ressources-pour-la-gdr-dans-les-etablissements/\"><span style=\"font-weight: 400;\">personne ressource</span></a> <span style=\"font-weight: 400;\">ou contactez le Coordonnateur du PGD &agrave; </span><a href=\"mailto:support@portagenetwork.ca\"><span style=\"font-weight: 400;\">support@portagenetwork.ca</span></a>.</p>"

preservation = 'Preservation'
preservation_question_text = 'Des co&ucirc;ts sont-ils associ&eacute;s au choix du lieu de d&eacute;p&ocirc;t et &agrave; la pr&eacute;paration des donn&eacute;es?'
preservation_guidance = "<p><span style=\"font-weight: 400;\">La pr&eacute;paration du mat&eacute;riel de recherche pour son &eacute;ventuelle conservation implique une vari&eacute;t&eacute; de t&acirc;ches pouvant pr&eacute;senter des co&ucirc;ts qu&rsquo;il est pr&eacute;f&eacute;rable de budg&eacute;tiser dans la demande de financement. &Agrave; cette fin, un </span><a href=\"https://www.curationexchange.org/understand-your-costs/19-summary-of-cost-models\"><span style=\"font-weight: 400;\">mod&egrave;le de co&ucirc;ts</span></a><span style=\"font-weight: 400;\"> peut-&ecirc;tre utile ou simplement les rubriques de base du </span><a href=\"https://ukdataservice.ac.uk/media/622368/costingtool.pdf\"><span style=\"font-weight: 400;\">UK Data Service Costing Tool</span></a><span style=\"font-weight: 400;\"> (</span><em><span style=\"font-weight: 400;\">liens en anglais</span></em><span style=\"font-weight: 400;\">).</span></p>\r\n<p><span style=\"font-weight: 400;\">Int&eacute;grer cette estimation de co&ucirc;t dans la section </span><em><span style=\"font-weight: 400;\">Responsabilit&eacute;s et ressources</span></em><span style=\"font-weight: 400;\">.</span></p>\r\n<p><span style=\"font-weight: 400;\">Consulter au besoin une </span><a href=\"https://portagenetwork.ca/fr/outils-et-ressources/personnes-ressources-pour-la-gdr-dans-les-etablissements/\"><span style=\"font-weight: 400;\">personne ressource</span></a><span style=\"font-weight: 400;\"> ou contactez le Coordonnateur du PGD &agrave; </span><a href=\"mailto:support@portagenetwork.ca\"><span style=\"font-weight: 400;\">support@portagenetwork.ca</span></a><span style=\"font-weight: 400;\">.</span></p>"


template_ids = Template.where(title: template_title, locale: template_locale).pluck(:id)

# Get French db entries for phase 1 of this template
phase_one_ids = Phase.where(template_id: template_ids, number: 1).pluck(:id)
sharing_and_reuse_ids = Section.where(phase_id: phase_one_ids, title: sharing_and_reuse).pluck(:id)
question_ids = Question.where(section_id: sharing_and_reuse_ids).pluck(:id)
sharing_and_reuse_questions = Question.where(id: question_ids, text: sharing_and_reuse_question_text)
sharing_and_reuse_annotations_1 = Annotation.where(question_id: question_ids, text: sharing_and_reuse_example_answer)
sharing_and_reuse_annotations_2 = Annotation.where(question_id: question_ids, text: sharing_and_reuse_guidance)

# Get French db entries for phase 2 of this template
phase_two_ids = Phase.where(template_id: template_ids, number: 2).pluck(:id)
preservation_ids = Section.where(phase_id: phase_two_ids, title: preservation).pluck(:id)
question_ids = Question.where(section_id: preservation_ids).pluck(:id)
preservation_questions = Question.where(id: question_ids, text: preservation_question_text)
preservation_annotations = Annotation.where(id: question_ids, text: preservation_guidance)
```

**Comment by closenma** [comment]
Per our conversation in the stand up today, I'm advising that changes to links in the template are complete and published out. @aaronskiba I'm hands off this template until you're done now.
