### ISSUE TITLE
Request feedback phrase displaying in English when French is toggled

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#494]
A sentence on the panel to request feedback on a plan is displaying in English when French is toggled.

![image006](https://github.com/portagenetwork/roadmap/assets/30664432/3e9ffc25-794a-4a16-b8db-a003330d6ea9)

This seems to be nonspecific to template, but let me know if I should ask the user for the template they are using. 

Do we have a translation for this segment in translation.io? If not, I will request one from our translation team.

Tagging @lagoan for triage

**Comment by aaronskiba** [comment]
Hi @isawil,

We are missing a corresponding fr-CA translation for this in translation.io ([here](https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=5ee58254&query=Click%20below%20to%20give%20data%20management%20staff)). I've added a `missing` tag for it.

**Comment by aaronskiba** [comment]
Hi @shilowil,

I was just doing some housekeeping on old issues and noticed we still need to provide a translation for the following:

`
Click below to give data management staff at %{owner_org}, the Plan Owner's org, access to read and comment on your plan.
`

**Comment by aaronskiba** [comment]
This translation is now working:
![Screenshot from 2024-06-18 15-03-57](https://github.com/portagenetwork/roadmap/assets/71047780/0c8f72ba-1bf2-429f-a3f3-e1e417d539b1)
