### ISSUE TITLE
Missing Translations For Browser Tab Titles + Incoming Upstream Releases

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#508]
While fixing the ampersand issue with the Plan Titles, I also enabled some more translations for browser tab titles.

Here is a list of those entries (I've also added the _missing_ tag to each of them on translation.io):

```
%{plan_title} - Download
%{plan_title} - Request feedback
%{plan_title} - Share
%{plan_title} - Write plan
%{plan_title} - add contributor
%{plan_title} - add research output
%{plan_title} - contributors
%{plan_title} - edit contributor
%{plan_title} - edit research output
%{plan_title} - research outputs
```

**Comment by aaronskiba** [comment]
Here is a list of entries from upstream releases 4.0.0, 4.0.1, and 4.0.2 (missing tags have been added on translation.io):
```
Review organisational plans
Research Outputs:
Research output type
File size units
Select a subject area
Select a repository type
Terms of Use
```
I should mention that there are some very close translations already existing on translation.io. For example, we already have a translation for `Research Outputs` (no `:`) [here](https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=97087385&query=Research%20Outputs):

**Comment by lagoan** [comment]
@isawil to share with the translation team.

**Comment by shilowil** [comment]
I've received the following translations:

Download | Télécharger
Request   feedback | Demander un retour d'information
Share | Partager
Write plan | Rédiger un plan
add   contributor | Ajouter une contributrice ou un contributeur
add research   output | Ajouter un résultat de recherche
contributors | Contributrices ou contributeurs
edit   contributor | Éditer une contributrice ou un contributeur
edit research   output | Éditer un résultat de recherche
research   outputs | Résultats de recherche
Review   organisational plans | Réviser les plans organisationnels
Research   Outputs: | Résultats de recherche
Research   output type | Type de résultats de recherche
File size   units | Unités de taille du fichier
Select a   subject area | Sélectionner un domaine
Select a   repository type | Sélectionner un type de dépôt
Terms of Use | Conditions d'utilisation

**Comment by aaronskiba** [comment]
I've gone ahead and added all of the French translations on translation.io. This issue is now completed.
