### ISSUE TITLE
Remove 'en-GB' From translation.io Locales

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#516]
Our language dropdown only includes 'en-CA' and 'fr-CA'. I don't think there is any need to include 'en-GB' as a target locale on translation.io. (Also, it is costing money to store 'en-GB' translations).

![Screenshot from 2023-10-24 10-57-14](https://github.com/portagenetwork/roadmap/assets/71047780/4cdcfe4f-c706-4789-b321-4bb647d72661)

**Comment by lagoan** [comment]
This is done on #474
