### ISSUE TITLE
Incoming Translations For 'template header error' From Upstream

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#517]
One of the incoming changes from the upstream releases is a modification to the file [translation.fr-CA.yml](https://github.com/portagenetwork/roadmap/blob/42b6a662cf74e084fb1c08bb0006fb0d81e1d8bf/config/locales/translation.fr-CA.yml#L122). This modification would update French translations for the "Template Header Error" message.

Should we accept these changes? Currently, the file is using our current translations and the incoming translations are commented out. Should I leave it that way? Or would we prefer the incoming translations? Thank you.
```
# OPTION 1: OUR CURRENT TRANSLATIONS
one: 'Impossible d''enregistrer ce(tte) %{model} : 1 erreur'
other: 'Impossible d''enregistrer ce(tte) %{model} : %{count} erreurs'

# OPTION 2: NEW INCOMING TRANSLATIONS
one: " 1 erreur a empêché l’enregistrement de %{model}"
other: "%{count} erreurs ont empêché l’enregistrement de %{model} "
```

**Comment by lagoan** [comment]
@aaronskiba lets keep the original translations.

**Comment by aaronskiba** [comment]
This was addressed via PR https://github.com/portagenetwork/roadmap/pull/474.
(Additional Note: I don't think this file should've been manually edited anyway. Rather, it should be set automatically when the sync task is run with `disable_yaml` set to false.
