### ISSUE TITLE
Enable Translations For Template Question Options

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#537]
Even when French is selected in the language selector, template question options render in English ('Yes' 'No' within screenshots):
![Screenshot from 2023-11-22 09-02-38](https://github.com/portagenetwork/roadmap/assets/71047780/cc0fe57e-60e7-4dd1-90c9-1875715bbbce)
![Screenshot from 2023-11-22 09-10-37](https://github.com/portagenetwork/roadmap/assets/71047780/2d790b01-f904-462e-bb41-fd478aa4c84b)

**Comment by lagoan** [comment]
This is a configuration change. PR is ready to go.
