### ISSUE TITLE
Copying a template does not copy the template's annotations

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#54]
**Expected behavior:**

When copying a template, the full content should be recreated.

**Actual behavior:**

The copied template does not contain the question-specific annotations.

**Steps to reproduce:**

Copy a template and the annotations will not be present.

**Comment by lagoan** [comment]
@pengyin-shan is this still an issue ?

**Comment by pengyin-shan** [comment]
Not see this error after the 3.0 release. close it for now.
