### ISSUE TITLE
"Please include an '@' in the email address." Alert Not Translating

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#550]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
3.3.1+portage-3.2.2

**Steps to reproduce:**
1. Select French Language
2. Try to create a new account, but don't include an @ symbol when providing an email.

![Screenshot from 2023-12-07 14-41-50](https://github.com/portagenetwork/roadmap/assets/71047780/71c2b21d-9e6a-4073-9f20-8209095c2e76)

A solution may be provided here: https://github.com/logaretm/vee-validate/issues/1595#issuecomment-422160662
Perhaps we don't want to address this until after the bootstrap upgrade is merged?

**Comment by aaronskiba** [comment]
Testing same error in Safari:
![Screenshot 2023-12-07 at 3 07 18 PM](https://github.com/portagenetwork/roadmap/assets/71047780/6f2c9455-b090-4d9e-8ff3-84406b443721)

(No error appears to render when using Firefox.)

**Comment by aaronskiba** [comment]
The following code change disables the html validation and results in the following when the email `a` is provided:
![Screenshot from 2023-12-07 15-37-39](https://github.com/portagenetwork/roadmap/assets/71047780/f15e0879-fa93-4bd5-ad08-e85b96b38cb5)

![Screenshot from 2023-12-07 15-36-49](https://github.com/portagenetwork/roadmap/assets/71047780/634052de-337a-4478-9826-267872202966)

**Comment by lagoan** [comment]
Will leave it as is. Browser will take care of it.
