### ISSUE TITLE
Inconsistent Bundler Versions

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#600]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- 3.3.1+portage-3.2.2

The `3.3.1+portage-3.2.2` tagged commit (16b19cd82e35c9cf5560c1421c94587a46ac52c6) states the following in `Gemfile.lock`:
```
BUNDLED WITH
   2.4.15
```

The `Push Docker UAT image to Docker Hub` GitHub Action run for  `3.3.1+portage-3.2.2-uat-1` states the following:
```
#11 [ 6/15] RUN gem install bundler
#11 14.64 Successfully installed bundler-2.4.22
```
https://github.com/portagenetwork/roadmap/actions/runs/6933754380/job/18860543418

The `Push Docker image to Docker Hub` GitHub Action run for  `3.3.1+portage-3.2.2` states the following:
```
#11 [ 6/15] RUN gem install bundler
#11 23.61 Successfully installed bundler-2.4.21
```
https://github.com/portagenetwork/roadmap/actions/runs/6580250934/job/17877846639#logs

And the following findings were provided by Neil:

```
Tue 21 Nov 2023 09:27:34 AM MST
======== In Staging ============
== southampton: ==
dmp-3.2.2-0.x86_64
Bundler version 2.3.26
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
======== In Sandbox ============
== dmp-web-uat-1: ==
dmp-3.2.2-0.x86_64
Bundler version 2.3.26
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
======== In Prod ============
== dmp-web-prd-1: ==
dmp-3.2.2-0.x86_64
Bundler version 2.3.26
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
== dmp-web-prd-2: ==
dmp-3.2.2-0.x86_64
Bundler version 2.3.26
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
```

**Comment by lagoan** [comment]
@aaronskiba  and @nmacgreg will coordinate version changes
