### ISSUE TITLE
Modifications needed for new Sandbox environment

### ISSUE THREAD

**Issue by nmacgreg** [portagenetwork/roadmap#62]
When I use Ansible to bootstrap the new server for the "sandbox" environment, I run into problems that ought to be solved within the codebase, not within the Ansible playbook.  Note that in this environment, the database server will be "localhost".

**Expected behaviour:**
* ```RAILS_ENV=sandbox bundle exec rake db:version``` should not throw errors (it should fail if the database doesn't exist, and succeed without errors if it exists).  This is used to check whether to run the next command or not.
*  ```RAILS_ENV=sandbox bundle exec rake db:setup``` should not throw errors (it should create the database)

**Actual behaviour:**
These commands are throwing errors indicating that the environment named "sandbox" isn't defined yet, eg

* ```ActiveRecord::AdapterNotSpecified: 'sandbox' database is not configured.```
* ```RAILS_ENV=sandbox environment is not defined in config/webpacker.yml, falling back to production environment```

**Steps to reproduce:**

Run these commands as root on dmp-web-uat-1 in ~/dmp/:

* ```RAILS_ENV=sandbox bundle exec rake db:version```
* ```RAILS_ENV=sandbox bundle exec rake db:setup```

**Comment by pengyin-shan** [comment]
@nmacgreg I'm on it. Once I'm done with coding part I'll double check with Omar and merge with the uat code.

**Comment by pengyin-shan** [comment]
Modified code in issue62 branch. Will need to merge changes from integration branch once the node setup got fixed.
