### ISSUE TITLE
Address Template Handling For Super Admin Users

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#661]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- `4.0.2+portage-4.0.1`

**Change Affiliation**
- Super admin users are able to view/edit any template within the app. However, they must first manually set their org to match the org associated with the template via the `Change affiliation` option. This seems like it shouldn't be necessary.
![Screenshot from 2024-02-13 13-01-15](https://github.com/portagenetwork/roadmap/assets/71047780/7739aa18-bfd4-4646-b7b0-37eb9c888afb)

**View Templates**
- Despite the `Change affiliation` mechanism, a super admin can still view any template if they manually type its corresponding url. For example, if the template with id x is associated with a different org than the super admin is, the super admin can still navigate to it by entering `http://127.0.0.1:3000/org_admin/templates/x` within the browser.

**Comment by lagoan** [comment]
Will not fix
