### ISSUE TITLE
Update Rails.application.config.action_mailer.default_url_options

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#666]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- `4.0.2+portage-4.0.1`

**Issue**
- In production, `Rails.application.config.action_mailer.default_url_options` is still configured to the former `assistant.portage-network.ca` host. As a result, rather than `dmp-pgd.ca/link/to/page`, links to the app contained within emails state `assitant.portage-network.ca/link/to/page`. Luckily, our re-routing seems to always properly take the user to the corresponding `dmp-pgd.ca/link/to/page`, but this needs to be updated.

**Additional Notes**
- Currently, we are assigning this value via a secret in `config/application.rb`.
- DMPRoadmap also assigns this value in `config/application.rb`. However, rather than a secret, they implement the following ([DMPRoadmap's config/application.rb](https://github.com/DMPRoadmap/roadmap/blob/8a0d0fb1f56949f6d5861d8c91eb66ae201d0c0f/config/application.rb#L55)):

```ruby
config.action_mailer.default_url_options = { host: Socket.gethostname.to_s }
```

**Comment by lagoan** [comment]
@nmacgreg will update secret value with next deployment

**Comment by aaronskiba** [comment]
This change was implemented in production alongside the deployment of `4.0.2+portage-4.0.2`.
