### ISSUE TITLE
Clarify information from download file ino usage statistics page

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#68]
This change requires:

- [ ] Change name of the downloaded file
- [ ] Change the column name in the file content

On the usage statistics page, when downloading the file for "No. plans during last year", the file name is "completed_plans.csv".
This is is misleading/confusing.

The name should be changed to "created_plans.csv"

The file content also has a column called "Completed Plans". This should be changed to "Created Plans"

**Comment by lagoan** [comment]
It looks like there is another problem related to this issue.

The download button does not show up for organizational administrators on the current integration branch. Will need to look into this.

**Comment by pengyin-shan** [comment]
@robynnicholson this feature is in uat now. Please feel free to test it and let me know if there is anything unexpected. thanks!

**Comment by robynnicholson** [comment]
@pengyin-shan works for me! File name and column both changed to "created" rather than "completed" which is exactly what we were after. Thanks!

**Comment by portagenetwork** [comment]
> @pengyin-shan works for me! File name and column both changed to "created" rather than "completed" which is exactly what we were after. Thanks!

Thank you for confirmation! I will close this issue then
