### ISSUE TITLE
Portage Template not default/first template

### ISSUE THREAD

**Issue by closenma** [portagenetwork/roadmap#685]
Please complete the following fields as applicable:

User reports that the list appears out of order, and that historically Portage Template was first/default. This is also indicated on https://dmp-pgd.ca/about_us

This appears to be the case for my own account in the U of A org (screenshot here)
![Screenshot 2024-03-06 at 11 56 09 AM](https://github.com/portagenetwork/roadmap/assets/147545804/480270a6-b0a4-4720-81a5-1b7e5847ec5b)

Rather than the standard Portage Template, CRDCN template is showing up first (alphabetical order)

**Comment by lagoan** [comment]
The template selection drop down should have a specific order. The following is the order we used in the past:

- First the default template (Portage Template)
- The rest of the default organizations (Portage) templates
- The users own organizations templates

If an organization administrator customizes a template, then the customized template should now appear and not the original template.

For example.

The original list is:

- Portage Template
- Portage Template for Systematic Reviews
- Portage Template for Water Quality Research
- University of Alberta Template

Then an administrator from the University of Alberta customizes "Portage Template for Water Quality Research", The list will seem the same, but selecting "Portage Template for Water Quality Research" will take the user to that cusomized template.

- Portage Template
- Portage Template for Systematic Reviews
- Portage Template for Water Quality Research (Same title but now it directs to the customized version)
- University of Alberta Template

**Comment by aaronskiba** [comment]
It looks like the sorting is disregarding both the default template as well as the default organisation: 
![Screenshot from 2024-03-27 13-19-51](https://github.com/portagenetwork/roadmap/assets/71047780/b32541a7-be50-4402-8747-63a2eeed9c1e)
