### ISSUE TITLE
Translations on plan sharing pages

### ISSUE THREAD

**Issue by closenma** [portagenetwork/roadmap#695]
A user flagged that there are areas where English is showing up and some strange translations in a few of the places in French. 

In the French version of the Share section, we may need to bring translations back through in the translation tool. Screenshots are from the user, cross-reference with ticket #0222772 on help desk if needed.

![image002](https://github.com/portagenetwork/roadmap/assets/147545804/6f570faa-f5d7-4966-9ded-4650b237bbf3)
![image003](https://github.com/portagenetwork/roadmap/assets/147545804/efc67647-a017-4bcc-ab6f-54916f3ae721)
![image001](https://github.com/portagenetwork/roadmap/assets/147545804/9a34f929-5492-4f80-bcc4-4fa215618d22)

Tagging @aaronskiba as this seems to be part of translation fixes that might still be on-going

**Comment by aaronskiba** [comment]
I can see that within the `dmp-assistant` project on translation.io, the French translation is missing for `"Click below to give data management staff at %{owner_org}, the Plan Owner's org, access to read and comment on your plan."`
https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=5ee58254&query=Click%20below%20to%20give%20data%20management%20staff%20at

However, there are two existing translations within the `dmp-assistant-test` project:
https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=5ee58254&query=Click%20below%20to%20give%20data%20management%20staff%20at%20%25%7Bowner_org%7D%2C%20the%20Plan%20Owner%27s%20org%2C%20access%20to%20read%20and%20comment%20on%20your%20plan.

Maybe we can just go ahead and copy over the one without the `<p>` `</p>` tags?

**Comment by aaronskiba** [comment]
Regarding the translation of `"Public or organisational visibility is intended for finished plans. You must answer at least %{percentage}%% of the questions to enable these options. Note: test plans are set to private visibility by default."`, it looks like this translation is an outstanding issue requiring review:

![Screenshot from 2024-03-21 14-08-35](https://github.com/portagenetwork/roadmap/assets/71047780/489af9c9-85d1-4836-ab70-fa05632fce01)

https://translation.io/ualbertalib/dmp-assistant/fr-CA?query=Public%20or%20organisational%20visibility%20is%20intended%20for%20finished%20plans.%20You%20must%20answer%20at%20least%20%25%7Bpercentage%7D%25%25%20of%20the%20questions%20to%20enable%20these%20options.%20Note%3A%20test%20plans%20are%20set%20to%20private%20visibility%20by%20default.

**Comment by aaronskiba** [comment]
I've gone ahead and copied over the `dmp-assistant-test` project translation.

> I can see that within the `dmp-assistant` project on translation.io, the French translation is missing for `"Click below to give data management staff at %{owner_org}, the Plan Owner's org, access to read and comment on your plan."` https://translation.io/ualbertalib/dmp-assistant/fr-CA?segment=5ee58254&query=Click%20below%20to%20give%20data%20management%20staff%20at
> 
> However, there are two existing translations within the `dmp-assistant-test` project: https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=5ee58254&query=Click%20below%20to%20give%20data%20management%20staff%20at%20%25%7Bowner_org%7D%2C%20the%20Plan%20Owner%27s%20org%2C%20access%20to%20read%20and%20comment%20on%20your%20plan.
> 
> Maybe we can just go ahead and copy over the one without the `<p>` `</p>` tags?

**Comment by aaronskiba** [comment]
Closing this issue. A missing translation remains to be provided, but it has been added to the following ticket: https://github.com/portagenetwork/roadmap/issues/698
