### ISSUE TITLE
Multiphase Plan Download/Export Option

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#70]
When downloading a plan, the current behaviour is to download a single phase

![image](https://user-images.githubusercontent.com/1537909/143292434-452f9858-0fb9-49b2-a9a0-5c795b2739b3.png)

We need to add an option to download all phases where it makes sense.

CSV files may be problematic because they represent a tabular view of the data. For that instance, we can think about building a zip file with all of the files there.

For now, add the option for multiphased download to 

- [ ] html
- [ ] pdf
- [ ] text
- [ ] docx
- [x] #75

And disable the option to multiphased download when CSV format is selected.

Will deal with CSV in another ticket.

**Comment by pengyin-shan** [comment]
@lagoan  currently there is no phase selection for JSON (and we are not displaying phase information in json). Should I add it? if so I'll add it as a separate ticket

**Comment by lagoan** [comment]
You are right @pengyin-shan, we should add this change on another ticket, same as with the CSV download.

**Comment by pengyin-shan** [comment]
Cool, I'll add it as a separate ticket. For now, I'm keeping original setting: JSON has no phase selection. CSV has phase selection but no 'All Phase' selection for user

**Comment by pengyin-shan** [comment]
@robynnicholson : this feature is in uat now. Feel free to test it and let me know if you notice anything unexpected. thanks!

**Comment by robynnicholson** [comment]
@pengyin-shan works perfectly for me, thank you! Just to clarify, judging by yours and @lagoan's comments on this issue thread, and through testing, "All Phases" is a download option for all file format types except CSV and JSON? Otherwise, I've tried downloading other file formats and they look great!

**Comment by pengyin-shan** [comment]
> @pengyin-shan works perfectly for me, thank you! Just to clarify, judging by yours and @lagoan's comments on this issue thread, and through testing, "All Phases" is a download option for all file format types except CSV and JSON? Otherwise, I've tried downloading other file formats and they look great!

Yes. Sorry I should give you a overview first..."All Phases" is a download option for all file format types except CSV and JSON for now. If you switch to JSON and CSV this option should be hidden. CSV and JSON requires different feature development, so this ticket we only gonna to take care of DOCX, PDF, TXT and HTML

**Comment by robynnicholson** [comment]
That makes sense, thank you for clarifying! All looks good to me :)

**Comment by pengyin-shan** [comment]
> That makes sense, thank you for clarifying! All looks good to me :)

Thank you! I'll close this issue then
