### ISSUE TITLE
DMP Assistant v4.1.0 UAT Testing

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#702]
Please complete the following fields as applicable:

**UAT Instance URL**
- https://uat.library.ualberta.ca:3001/

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- `v4.1.0`

**Explanation**
- The purpose of this GitHub Issue is to document any issues/concerns/etc. with respect to the upcoming `4.1.0+portage-4.1.0` release.

**Comment by aaronskiba** [comment]
The styling of the Create Guidance Textbox seems very faded.
![Screenshot from 2024-03-25 14-43-51](https://github.com/portagenetwork/roadmap/assets/71047780/9af9a862-ec25-41b3-a723-7616317ef59f)

- `dmp-pgd.ca`
- ![Screenshot from 2024-03-25 14-51-57](https://github.com/portagenetwork/roadmap/assets/71047780/8836d5e6-3355-4109-9522-1642d904d5e0)

- `uat.library.ualberta.ca:3001`
- ![Screenshot from 2024-03-25 14-52-26](https://github.com/portagenetwork/roadmap/assets/71047780/54daf4e1-e127-4055-8b8f-37ebdcd96e17)

https://www.tiny.cloud/blog/tinymce-skins-and-icons/

**Comment by closenma** [comment]
The template list order reported in issue #685 is still present in this version, the Portage Template should be first, but the list is showing up as alphabetical

**Comment by aaronskiba** [comment]
Amongst its changes, [DMPRoadmap Release v4.1.1](https://github.com/DMPRoadmap/roadmap/releases/tag/v4.1.1) mentions, `Added a .gitkeep file to the app/assets/builds directory to address potential issues when building the application.css file during production deploys.` (the related PR: https://github.com/DMPRoadmap/roadmap/pull/3314)

This change should be investigated while merging the v4.1.0 changes into DMP Assistant.

**Comment by aaronskiba** [comment]
Please note, the  https://uat.library.ualberta.ca:3001/ UAT instance is currently testing `4.0.2+portage-4.0.3`.

**Comment by aaronskiba** [comment]
It looks like the template ordering issue has returned:
<img width="667" alt="Screenshot 2024-06-05 at 1 13 22 PM" src="https://github.com/portagenetwork/roadmap/assets/71047780/498c7c99-f055-481b-bf67-b69e2a6ae158">

**Comment by aaronskiba** [comment]
> It looks like the template ordering issue has returned: <img alt="Screenshot 2024-06-05 at 1 13 22 PM" width="667" src="https://private-user-images.githubusercontent.com/71047780/336977357-498c7c99-f055-481b-bf67-b69e2a6ae158.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTU2ODMsIm5iZiI6MTcxNzYxNTM4MywicGF0aCI6Ii83MTA0Nzc4MC8zMzY5NzczNTctNDk4YzdjOTktZjA1NS00ODFiLWJmNjctYjY5ZTJhNmFlMTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE5MjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YTczYzZmZGMwYzI2NDFmYTk4NGU3MWFjMWNjMGJjZTI5NGRjYmMyOWVlYTk2ZDdlM2FhZDQxMGMwMmJmZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YN_qE_ubtkEFaM_4x4xkgZ8tWVyJYgD5YINYMkG_qKU">

![Screenshot from 2024-06-05 13-21-52](https://github.com/portagenetwork/roadmap/assets/71047780/74d7ae99-7e1a-4c19-8d20-d492153b8006)
![Screenshot from 2024-06-05 13-22-11](https://github.com/portagenetwork/roadmap/assets/71047780/12c06ef9-e94f-47d4-92cd-d5eb4ad94de5)

<img width="667" alt="Screenshot 2024-06-05 at 1 13 22 PM" src="https://github.com/portagenetwork/roadmap/assets/71047780/2492ba7f-1d67-42f5-8ce2-152118c23da7">

After looking more closely, it appears that this ordering was merely the result of the "out-of-order" template being set to private (rather than public) visibility.
