### ISSUE TITLE
4.0.2+portage-4.0.3 UAT Testing

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#715]
Please complete the following fields as applicable:

**UAT Instance URL**
- https://uat.library.ualberta.ca:3001/

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- `4.0.2+portage-4.0.3-uat-1`

**Explanation**
- The purpose of this GitHub Issue is to document any issues/concerns/etc. with respect to the upcoming `4.0.2+portage-4.0.3` release.

**Comment by aaronskiba** [comment]
- This release includes a change to now enable monitoring on rollbar.com.
  - The following "Test message" was successfully executed within the Rails console corresponding to the UAT instance:
![Screenshot from 2024-04-10 09-40-23](https://github.com/portagenetwork/roadmap/assets/71047780/4173f24c-8f9b-40d4-a602-8dfc07147534)

**Comment by aaronskiba** [comment]
Terms and conditions check is now present on the invitation link form
![Screenshot from 2024-04-10 09-55-47](https://github.com/portagenetwork/roadmap/assets/71047780/513d09b3-8999-4f13-a327-e7b51c900eeb)

User cannot proceed when the terms and conditions box is unchecked (this is the desired behaviour):

![Screenshot from 2024-04-10 09-57-14](https://github.com/portagenetwork/roadmap/assets/71047780/6b4bdee3-61e4-4ff2-a5bb-291f2e5a1df3)

User is logged in successfully after checking the box:
![Screenshot from 2024-04-10 10-00-59](https://github.com/portagenetwork/roadmap/assets/71047780/e5831fc3-f15c-476d-9238-5f025aae2cb7)

Desired behaviour is observed when checking rails console before and after the invitation link is submitted successfully:

```terminal
irb(main):002:0> User.last.accept_terms
=> nil
irb(main):003:0> User.last.accept_terms
=> true
irb(main):004:0>
```

**Comment by closenma** [comment]
On the list ordering issue that was flagged, I noticed that if you select no organization using the check-box, the list is out of order. Otherwise the list appears to have the normal Portage Template first order.
<img width="1402" alt="Screenshot 2024-04-10 at 12 34 02 PM" src="https://github.com/portagenetwork/roadmap/assets/147545804/f666b11a-34ec-4965-a314-cd8195bf2c92">

**Comment by aaronskiba** [comment]
A new UAT instance is now up. It addresses the template ordering when the "No research organization" box is checked off.
