### ISSUE TITLE
Unwanted Behaviour With Template.visibility Checkbox

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#754]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
`4.0.2+portage-4.0.3`

**Expected behaviour:**
The template visibility checkbox should render as checked when Template.visibility == organizational and unchecked when Template.visibility == public.

**Actual behaviour:**
The checkbox is able to toggle the visibility between organizational and public. Unfortunately, regardless of the value of Template.visibility, whenever the page is refreshed, the checkbox renders as unchecked.

![Screenshot from 2024-05-15 15-39-55](https://github.com/portagenetwork/roadmap/assets/71047780/4e28e86b-864a-42a7-b72b-ee7b2acecc7d)

**Comment by lagoan** [comment]
@200455939-yashu will take a look at PR.
