### ISSUE TITLE
Change label to Plan visibility public plan

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#81]
**Expected behaviour:**

We need to clarify what public visibility will mean for public created plans. 

We should change the description to: 

```Public: this will make plans publicly available from Public DMPs page, viewable and downloadable by other users```

**Actual behaviour:**

Currently, the plan visibility description says `Public: anyone can view`

![image](https://user-images.githubusercontent.com/1537909/144309898-d4f79652-5ffa-40d9-815f-a09846db1a30.png)

**Steps to reproduce:**

Log in
From the dashboard select a created plan
From the Plan, view click on the Share tab
The set plan visibility will have the list of visibilities available for plans.

**Comment by pengyin-shan** [comment]
@lagoan just to confirm, we don't have a translation for 'this will make plans publicly available from Public DMPs page, viewable and downloadable by other users' in translation.io yet, should I discuss this sentence with any professional translator?  Or I continue to use the one-word translation such as 'Público'?

**Comment by pengyin-shan** [comment]
@lagoan : I tested the translation in `dmp-assistant-test` project as following:
![Screen Shot 2021-12-03 at 5 00 39 PM](https://user-images.githubusercontent.com/92752107/144678522-6d1929cb-6880-494d-b933-ce5402d7d896.png)
But I didn't do anything to `dmp-assistant` project in case I disrupt the production version. So in order to get a correct translation in `dmp-assistant`, should I just add the sentence and msg Robyn for her approval?

**Comment by lagoan** [comment]
The translation files need to be resynched after they are updated in translation.io . Curerently this requires running a rake task to download the new content.

For now, I would suggest contacting @robynnicholson to make sure that translation is handled by our team of translators.

We will not be working on the translation side of the project unless it requires technical input.

I believe the rake task is `rake translation:sync`. Before running it make sure the api token points to the test project.

Let me know if I can clarify anything.

**Comment by pengyin-shan** [comment]
@lagoan Got it. Yeah I ran the `rake translation:sync` and got the translation I need in development environment for `dmp-assistant-test`.

So I think my next step is to contact @robynnicholson to confirm the translation in `dmp-assitant-test`, then after she confirmed, I can sync with `dmp-assistant` to make the new term being uploaded to `dmp-assistant`. I then add the same translation and sync again with `dmp-assistant` this time. Is this the workflow I should go?

**Comment by lagoan** [comment]
For now just to have her double check the translation
We will update the translation in the production project once everything is translated

For now don't update the translation files

**Comment by pengyin-shan** [comment]
Changes merged to integration branch and deployed in uat. Close this ticket
