### ISSUE TITLE
Breaking Changes After Renaming `"Portage Network"` Org Within App

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#813]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- `4.1.1+portage-4.1.0-uat-6` `4.1.1+portage-4.1.0-alpha-4`

**Expected behaviour:**
- To go along with the in-progress rebranding changes, a user with sufficient privileges should be able to rename `Portage Network` to `The Alliance`.

**Actual behaviour:**
- If `Portage Network` is renamed, breaking changes result. One of which is the inability to create a new plan within the app. After selecting an organisation, the message  `Unable to find a suitable template for the research organization and funder you selected.` is rendered (see screenshots):
- ![Screenshot from 2024-07-02 11-49-58](https://github.com/portagenetwork/roadmap/assets/71047780/a6dc30cf-56c7-4388-b017-99f4584b908d)
- ![Screenshot from 2024-07-02 11-52-29](https://github.com/portagenetwork/roadmap/assets/71047780/a671ba09-0671-4ef3-879a-59afbacfd0c6)
- ![Screenshot from 2024-07-02 11-50-53](https://github.com/portagenetwork/roadmap/assets/71047780/ec5b35fc-7d36-42c2-84c7-98f5f38d4bb3)

**Comment by aaronskiba** [comment]
This unwanted behaviour can be traced back to our usage of `default_funder_name: <%= ENV['DEFAULT_FUNDER_NAME'] %>` throughout the app. `default_funder_name: "Portage Network"` is hard-coded within our `secrets.yml`. As a result, breaking changes occur when we rename that Org within the app.

**Comment by lagoan** [comment]
Related to #815
