### ISSUE TITLE
Add popover information to Organization details view

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#82]
We need to clarify what `Organization type(s)` means on the Organization details page.

Add Floatover Text for "Organization type(s)" field on Organization details page (e.g., "This information can only be changed by a system administrator. Contact support@portagenetwork.ca if you have questions or to request changes.")

The floatover text should appear in the same what that the floatover text appears for Organization URLs.

To see this view
- Log into the system as an organizational administrator
- On the Admin menu select Organization details
- Scroll down to see `Organization type(s)`

![image](https://user-images.githubusercontent.com/1537909/144311500-da5087b8-d800-4927-a0e5-594efa26fcee.png)

**Comment by pengyin-shan** [comment]
@lagoan I made the change using example string `This information can only be changed by a system administrator. Contact support@portagenetwork.ca if you have questions or to request changes.`in branch #issue62, just want to confirm we gonna to also need a translation for this string right (I will update translation.io and add tag)? Or I should ask Robyn to propose a new English string first?

**Comment by lagoan** [comment]
That is great! 
When making the change of text, make sure you are using `Rails.configuration.x.organisation.email` to fetch the email address, we may change the contact email at some point and it would be great if there if we need to change it in only one place (I do know that it is hardcoded in other areas but we should avoid it whenever possible).

We will need the translated string. For now, synchronize the translation files and tag the new key.

**Comment by pengyin-shan** [comment]
Modified code to use `Rails.configuration.x.organisation.email`. Robyn has been notified for the translation in https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=6a0bca3d&query=This%20information%20can%20only%20be%20changed%20by%20a%20system%20administrator.%20Contact%20%25%7Bsupport_email%7D

**Comment by robynnicholson** [comment]
@pengyin-shan @lagoan Hi both, just following up on this issue, the translation has been added and verified in the dmp-assistant-test project on translation.io. Thanks!

**Comment by pengyin-shan** [comment]
Great, I will close this ticket then, thanks for confirmation!

> @pengyin-shan @lagoan Hi both, just following up on this issue, the translation has been added and verified in the dmp-assistant-test project on translation.io. Thanks!
