### ISSUE TITLE
Make 'Funding status' dropdown being a required field

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#86]
1. As discussed with Robyn in Slack, making the 'Funding status' dropdown menu on the 'Project Details' page to be a required field.
2. Add validation for this feature.

**Comment by pengyin-shan** [comment]
![Screen Shot 2021-12-07 at 16 47 46](https://user-images.githubusercontent.com/92752107/145111302-5ae57c53-e495-4130-8342-194bfb8a8ad5.png)

@robynnicholson  a default validation box will look like this (in my firefox) if someone doesn't select from the dropdown and try to save plan. Do you want any styling to the validation box or make any changes to this default wording?

**Comment by robynnicholson** [comment]
Thanks for looking into this @pengyin-shan! So just to clarify, the user must make a selection from the dropdown in order to complete the save of their plan?

**Comment by pengyin-shan** [comment]
@robynnicholson  if we set this field is required then user must select from drop-down list. If we don't want it to be required (as we said today in Slack) this behaviour will be disabled (which I think this is uat's default setting now).

**Comment by pengyin-shan** [comment]
This field is supposed to be not required. Close the ticket and maintain current behaviour
