### ISSUE TITLE
CILogon SSO Final Steps / Testing

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#862]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- Upcoming release `4.1.1+portage-4.1.4`

**Steps Remaining**
- [x] Rename SSO button from current "Sign in with ORCID iD"
- [x] In `config/initializers/devise.rb`,`config.omniauth :openid_connect, {`
  - [x] add `:email` to `scope: [`
  - [x] Add handling so `redirect_uri:` value always corresponds with url of app instance
- [x] Register all `config/initializers/devise.rb`,`config.omniauth :openid_connect, { redirect_uri:` values within CILogon application configuration
- [x] Add handling for when a user attempts to sign in with SSO using an email that does not yet exist within the `users` table.
- [x] Add script / rake task for creating a CILogon entry within `identifier_schemes` table.
- [x] Address https://github.com/portagenetwork/roadmap/issues/862#issuecomment-2318245905

**Comment by aaronskiba** [comment]
**Issue**
1. Log-in to DMP Assistant, navigate to "Edit Profile", and click "Link your institutional credentials"
  - <img width="1110" alt="Screenshot 2024-08-29 at 9 48 53 AM" src="https://github.com/user-attachments/assets/3b78b6ce-d6cf-4c6b-89fb-2f679109dff1">

2. Select "Google" as an identity provider (others may work too) and choose an account whose email DOES NOT already exist within DMP Assistant
  - <img width="490" alt="Screenshot 2024-08-29 at 9 49 38 AM" src="https://github.com/user-attachments/assets/2d5d2ee5-20dd-430a-b0a9-1b677941ab18">

3. After the account links successfully, logout out of the app, and then choose "Sign in with CILogon"
  - <img width="569" alt="Screenshot 2024-08-29 at 9 50 11 AM" src="https://github.com/user-attachments/assets/2c9cc0c9-69ab-45e4-ab78-2f1da53ccbd0">

4. Select "Google" as an identity provider and choose the same account you selected in step 2
  - <img width="661" alt="Screenshot 2024-08-29 at 9 50 17 AM" src="https://github.com/user-attachments/assets/d033421f-f895-4106-8077-298f94be7845">

5. Rather than logging back into the account you were previously logged into, the app creates a new account based on the account you chose in step 2/4 and logs you into that one
  - <img width="748" alt="Screenshot 2024-08-29 at 9 50 58 AM" src="https://github.com/user-attachments/assets/de42beb3-955d-438e-b5b3-72efe6dcedae">

**Comment by lagoan** [comment]
I was not able to replicate this behaviour. I followed these steps:

1. Created local account with ualberta email
2. Linked it with institutinoal credentials on profile page with gmail account
3. logged out
4. Logged in with CILogon using gmail account
5. Checking the profile page still shows my ualberta account

No new accounts were created.

@aaronskiba Please let me know if I missed some step

**Comment by aaronskiba** [comment]
> I was not able to replicate this behaviour. I followed these steps:
> 
> 1. Created local account with ualberta email
> 2. Linked it with institutinoal credentials on profile page with gmail account
> 3. logged out
> 4. Logged in with CILogon using gmail account
> 5. Checking the profile page still shows my ualberta account
> 
> No new accounts were created.
> 
> @aaronskiba Please let me know if I missed some step

Hi, sorry, I seem to be unable to replicate this error now. Maybe the edits to the identifier_schemes entry resolved it?

**Comment by aaronskiba** [comment]
`"Institutional credentials"` may need to be renamed. This is because a user is able to link something like a basic, non-institutional Gmail account:

Also, `http://cilogon.org/serverE/users/:id` should be updated to something more helpful (e.g. the email address of the linked account).

![Screenshot from 2024-08-30 15-29-58](https://github.com/user-attachments/assets/67c8fec2-7c3b-43c1-a72f-142f04296af6)

**Comment by lagoan** [comment]
@aaronskiba Could you create a ticket for making the linked accounts text more helpful? We can close this ticket after that new ticket is done.

**Comment by lagoan** [comment]
This was due to database garbage.
