### ISSUE TITLE
New Translation Segments For Release `4.1.1+portage-4.2.0`

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#888]
**Here is a list of the newly added segments for release `4.1.1+portage-4.2.0`:**

```
Invalid date format. please use YYYY-MM-DD when supplying `start` or `end` params.

Something went wrong, Please try signing-up here.

Linked succesfully

The current %{description} iD has been already linked to a user with email %{email}

Administrator privileges updated in %{tool_name}

Unlink your account from %{scheme_description}. You can link again at any time.

Are you sure you want to unlink %{scheme_description} ID?

Sign in with CILogon

DMP Assistant has recently implemented single sign on, which will allow you to use CI Logon to use institutional or social accounts in order to sign into your DMP Assistant account.

For help with single sign-on, help documents are available in <a href="%{sso_english_guidelines_url}"> English </a> and in <a href="%{sso_french_guidelines_url}"> French</a>.

CILogon
```

**Comment by closenma** [comment]
@aaronskiba I don't know if we can updated this, but there's small changes in the second and third English strings:
signing-up should be signing up (not hyphenated in this sentence construction)
successfully is misspelled in the phrase "Linked succesfully"

Will get the French for these ASAP

**Comment by aaronskiba** [comment]
> @aaronskiba I don't know if we can updated this, but there's small changes in the second and third English strings: signing-up should be signing up (not hyphenated in this sentence construction) successfully is misspelled in the phrase "Linked succesfully"
> 
> Will get the French for these ASAP

Sounds good and thanks for feedback. We will make sure these are corrected for the upcoming release. :)

**Comment by closenma** [comment]
Translations back from Alliance:

Format de date non valide. Veuillez utiliser le format AAAA-MM-JJ lorsque vous saisissez les paramètres `début` ou `fin`.

Une erreur s'est produite. Veuillez essayer de vous inscrire ici.

Relié avec succès

Cet identifiant %{description} a déjà été associé à un utilisateur dont l'adresse électronique est %{email}.

Les privilèges de l'administrateur ont été mis à jour dans %{tool_name}

Déliez votre compte de %{scheme_description}. Vous pouvez le relier à nouveau à tout moment.

Êtes-vous sûr de vouloir supprimer le lien %{scheme_description} ID ?

Ouvrir une session au moyen  de CILogon

L'Assistant PGD a récemment mis en place un système d'authentification unique, qui vous permettra de passer par CI Logon pour utiliser des comptes institutionnels ou sociaux afin de vous connecter à votre compte de l'Assistant PGD.

Pour obtenir de l'aide sur l'authentification unique, des documents d'aide sont disponibles en  <a href=« %{sso_french_guidelines_url} »> français</a> et en<a href=« %{sso_english_guidelines_url} »> anglais </a>.

CILogon

A spreadsheet is available in the service team drive here: [https://docs.google.com/spreadsheets/d/1trZtmgd_jL2s_erCpWlpOUG5K4ktV01J/edit?usp=drive_link&ouid=101326528145328111974&rtpof=true&sd=true](https://docs.google.com/spreadsheets/d/1trZtmgd_jL2s_erCpWlpOUG5K4ktV01J/edit?usp=drive_link&ouid=101326528145328111974&rtpof=true&sd=true)

**Comment by aaronskiba** [comment]
These were added to translation.io prior to the deployment of `4.1.1+portage-4.2.0`. I had to make a couple of tweaks to the following string:
```
Pour obtenir de l'aide sur l'authentification unique, des documents d'aide sont disponibles en <a href=« %{sso_french_guidelines_url} »> français et en<a href=« %{sso_english_guidelines_url} »> anglais .
```
It seems to be working, but I'll soon share my changes in the spreadsheet you mentioned.
