### ISSUE TITLE
Unpublish Template Workflow for Admin

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#89]
**Expected behaviour:**
1. Org admin & Super admin can remove a template only if **no one is using it in a plan**. If admins try to do it, we will show an error message saying something like 'this template is using in a plan. You can only unpublish it'
2. Again, If a template is using by some, Org admin & Super admin can **unpublish it**. The status of the template will be changing to **unpublished**
3. Do we need to inform template user (the one who created plan using this template) something like 'Please not your template has been unpublished'?

@robynnicholson @lagoan : please let me know if the description above is what we want. I'll confirm in code and make changes if needed then. Thanks!

**Comment by robynnicholson** [comment]
Hi @pengyin-shan:
1. If this is the current behaviour/logic, then certainly an error message could be a good addition, perhaps "This template has been used to create a plan, and can no longer be removed. Templates in use may be unpublished or edited." 
2. This sounds correct to me. 
3. This would probably be a good idea as well, but may require some further discussion - I'll add it to the Change Request Registry - we may want to consider a similar notification message for when a template has been not only unpublished, but if it has been updated and changes have been published.

**Comment by pengyin-shan** [comment]
@robynnicholson good, I'll work on the 1) and 2) for now since we have confirmed request for it. let me know if 3) also need to be implemented.

**Comment by pengyin-shan** [comment]
1) Confirmed that in current version, the 'Remove' function in template is not available if a plan is using it. Thus we don't need to add notification for it
2) Confirmed that even a plan is using the template, the admin can still 'unpublish', no notification will be sent out. 

We also got test already in code:
![Screen Shot 2021-12-10 at 16 10 18](https://user-images.githubusercontent.com/92752107/145641751-13398061-f9fe-41e6-9c29-099b8dfc45ae.png)

So @robynnicholson if you could verify on uat and let me know if the behaviour is there that would be great. I think we don't need any code for this ticket if that's the case

**Comment by robynnicholson** [comment]
Hi @pengyin-shan, thank you for looking into this!. I have confirmed both behaviours are true in UAT 3000. I think we can close this ticket for now in that case, as the current behaviour makes sense and is not disruptive to users. That being said, I have still added an item to our Change Request Registry to talk about perhaps in the future considering a user notification whenever a template is unpublished or has changes published - requires some further discussion!

**Comment by pengyin-shan** [comment]
> 

Thanks for confirmation. We can add user notification as a new feature if we decide to do it in the future. For now I'll close this ticket.
