### ISSUE TITLE
Funder Status Check for 3.0 Release

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#90]
@lagoan  to confirm the issue about funding status we discussed in the meeting, we want to change the dropdown to textbox? Or we just need a translation?
![Screen Shot 2021-12-09 at 15 13 32](https://user-images.githubusercontent.com/92752107/145468902-6ca18cbf-d2a1-4ea6-8ca3-a531f96d08f0.png)

**Comment by pengyin-shan** [comment]
@robynnicholson could you verify this issue? do you want to check the appears of dropbox? or we need want a translation form items in dropdown?

**Comment by robynnicholson** [comment]
@pengyin-shan This dropdown can remain as is, it is the "Funder" field above it we want to change to a free-text textbox (as opposed to a "Type to select from a dropdown" field as it is in the UAT 3000 instance currently). For the "Funding status" field, we do need translations, yes. A quick search in the dmp-assistant-test project on translation.io indicates "Funding status" and "- Please select one -" are available as translatable entries, however I don't see "Planned," "Funded," or "Denied" there. Once those entries are there I can add the verified translations. Thanks!

**Comment by lagoan** [comment]
I will add tickets to address the issues of:

- Add funder status values to translation.io
- Change Funder filed to free-text textbox as it is in current deployed version

**Comment by pengyin-shan** [comment]
#93 reflected tasks of changing Funder auto-completion to free-text textbox. #99 reflected the translation.io task. close this issue accordingly
