### ISSUE TITLE
Wording of SSO button

### ISSUE THREAD

**Issue by closenma** [portagenetwork/roadmap#903]
With release of 4.2 we've received multiple requests to change the wording on the SSO button.

Recommended language "Sign in with institutional or social ID"

Can I get a read on how easily this can be done? Submitting string to Alliance translation and will provide ASAP.

**Comment by aaronskiba** [comment]
It's an easy update. Ideally, we'd want to do another release. But there is even a hack to update this without doing a release.

**Comment by closenma** [comment]
Button language

EN:
`Sign in with institutional or social ID`

FR:
`Ouvrir une session au moyen d'un identifiant institutionnel ou social`

Flagging this was related to #904 but is a higher priority if there is a way to fix rapidly, hoping that @lagoan can bring this up in the meeting today

**Comment by lagoan** [comment]
@200455939-yashu Please take a look at this as well
