### ISSUE TITLE
Translate values for Funding status

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#92]
The values for funding status are not being added to translation.io after synchronizing the code

This problem is mentioned in #90 

The reason these values are not showing up is that they are saved as an `enum` in the `plan` model as the flag `funding_status`.

https://github.com/portagenetwork/roadmap/blob/da1c9856154d7b0f8e65fe8d7901a8414e505524/app/models/plan.rb#L71-L74

Here are the values being used: 

https://github.com/portagenetwork/roadmap/blob/da1c9856154d7b0f8e65fe8d7901a8414e505524/app/views/plans/_project_details.html.erb#L170-L171

 The values to be used as text should be defined and used with the `_()` method in order for them to show up on translation.io .

A possible approach for this would be to handle the messages being displayed separately as we are doing with the visibility values:

https://github.com/portagenetwork/roadmap/blob/da1c9856154d7b0f8e65fe8d7901a8414e505524/app/models/plan.rb#L56-L64

**Comment by pengyin-shan** [comment]
@lagoan thank you, I'll modify code accordingly. Also for the changing to 'free-text' part of #90, did we mean type-in text field (like a auto-complete input field with only available options allowed?)

**Comment by lagoan** [comment]
For the end-user it will look like a text box. The back end will still have some logic in it but that is already implemented in a previous version. Will get back to you shortly with this.

**Comment by pengyin-shan** [comment]
Changes of code is done in issue92 branch.

@robynnicholson I uploaded 'planned', 'funded' and 'denied' terms to `dmp-assistant-test` and tag them as `needs review`. Please let me know when you confirm the translation and I'll sync again to get your update

**Comment by pengyin-shan** [comment]
translation task assigned in #99. close this issue
