### ISSUE TITLE
Revert Funder field to text box widget

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#93]
We need to change the current widget behavior on the Plan details edit view for the funder field.

Right now the view uses a custom widget that pulls information from the database as the user enters text into the text field. The widget shows a warning if the entered text does not match an entry in the system.

![image](https://user-images.githubusercontent.com/1537909/145885970-04152a7b-7c43-47b6-b663-78c291df224f.png)

The functionality needs to be reverted as it works on our current production instance. The widget is a simple text field widget where the user can enter any text she wants.

![image](https://user-images.githubusercontent.com/1537909/145886021-cac23298-4bea-4b0a-b332-ea7901fe8dc5.png)

The behaviour in the controller should remain the same as it is right now.

We will need to address an issue with usage statistics. This behaviour creates a new funder organization when a new value is entered, this will add noise to the current way the statistics are handled.

**Comment by pengyin-shan** [comment]
@lagoan ok, so we gonna to make this change and re-deploy to staging/production right?

**Comment by lagoan** [comment]
We can wait to redeploy this into staging/production for a bit.

Lets just gather more changes into integration and then push to UAT.

**Comment by pengyin-shan** [comment]
@lagoan what's the rule for funder id after we switch to text box? currently the auto-complete forces it to be an existing organization so we have org id already in our database. Should now we generate a new funder id every time user put something new?

**Comment by lagoan** [comment]
The org model has an `org_type` flag which can hold multiple values

https://github.com/portagenetwork/roadmap/blob/da1c9856154d7b0f8e65fe8d7901a8414e505524/app/models/org.rb#L169-L175

A Funder is an instance of the org model with the `org_type` value set to funder.

We will not need to check for funder_id.

I think the way to go would be to continue to use the method used in the plan controller where it creates an instance if needed, but one that does not show up on the listings.

**Comment by pengyin-shan** [comment]
@lagoan one more thing to confirm...we should hide the random organization created (i.e. unmanaged) from the list of creating a new plan right (in case too much noises raise like the following):
![Screen Shot 2021-12-15 at 17 58 20](https://user-images.githubusercontent.com/92752107/146277862-2e0ef7b1-6059-43fe-96db-5a148754b1c8.png)

And I think same idea should apply to all the org dropdown, such as when a new account is create and user statistics (we have a issue for it). If you agree, I will go through code to make sure all org dropddowns except the one on the project detail page show only managed org.

**Comment by pengyin-shan** [comment]
Close issue. Changes have been merged to the integration branch.
