### ISSUE TITLE
Fix usage statistics Org count

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#94]
Fixing issue #93 shows that all changes in a plan's funder create a new organization. This will add noise to the current way we are fetching statistics as we do not filter the count:

https://github.com/portagenetwork/roadmap/blob/8ab5afc91f49dbd6a1baeb39bd4be0e6e5632935/app/controllers/usage_controller.rb#L80-L82

We should look at how current listings for organizations ignore these created funders and follow the same way of doing it for presenting statistics.

**Comment by pengyin-shan** [comment]
Close issue. Changes have been merged to the integration branch.
