### ISSUE TITLE
Traslation Sync on Both UAT and Production

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#99]
@robynnicholson I will update the sync status to you in this ticket. I plan to

1. Sync the translation you marked yellow in Google Doc and push to uat
2. Once you confirm the translations are correct on uat, I'll sync again to upload the translation in uat to `dmp-assistant` translation.io (i.e. the source of translation for production environment)
3. Do a sync on production environment (I might need to contain Neil to do it) to download the translation in `dmp-assistant`

**Comment by pengyin-shan** [comment]
@robynnicholson I updated UAT. Could you please verify if the translations have been synced when you have time? Then I'll update production branch. thanks!

**Comment by robynnicholson** [comment]
Hi @pengyin-shan - just checked UAT 3000, the translations do not seem to have synced, unfortunately. The entries I know were added, translated and verified in translation.io (i.e., the "Funding Status" dropdown) are still in English, though the others in the Google doc list I sent are not yet in translation.io yet, which could be another issue.

**Comment by pengyin-shan** [comment]
@robynnicholson Ops let me check it...

**Comment by pengyin-shan** [comment]
@robynnicholson I updated UAT, could you let me know if you can see the translated version now?

**Comment by robynnicholson** [comment]
Hi @pengyin-shan, just checked UAT 3000, no translations are appearing, and no new entries on translation.io, unfortunately.

**Comment by pengyin-shan** [comment]
> Hi @pengyin-shan, just checked UAT 3000, the translations that are present in the dmp-assistant-test translation.io project are now showing (i.e., the "Funding Status" dropdown), however there are still untranslated strings that appear in English and that are not on translation.io yet.

Thank you @robynnicholson , so you are satisfied with the current translation on uat right? If so I will sync to the `dmp-assistant` translation.io instead of `dmp-assistant-test` as uat on now. After that, Neil can help us to grab new translation by restarting the production web server. We can choose to do it on this Friday or after the new year to avoid some auto-reboot accident on production server. 

Also just a note that some translations (such as *funding status*) require code-level changes to production server to reflect the new translations. That could take longer due to deployment complexity on production (not as simple as uat). I will let you know once we are ready to merge the code

**Comment by robynnicholson** [comment]
Hi @pengyin-shan - I am satisfied with the current translation on uat, yes. As you suggest, I think restarting the production server can wait until the new year, to avoid any errors or accidents over the break. 

Thank you for flagging the code-level translations. No rush on these at all, we can definitely address these more complex deployments in the new year.

**Comment by pengyin-shan** [comment]
> Hi @pengyin-shan - I am satisfied with the current translation on uat, yes. As you suggest, I think restarting the production server can wait until the new year, to avoid any errors or accidents over the break.
> 
> Thank you for flagging the code-level translations. No rush on these at all, we can definitely address these more complex deployments in the new year.

Ok, let's schedule the sync after the new year...in case unexpected accidents occurs and we gonna to have enough time to deal with it

**Comment by pengyin-shan** [comment]
Close issue. New translations in translation.io have been synced from `dmp-assistant-test` to `dmp-assistant`
